Oma cx kh
newrelic/newrelic-quickstarts pull request #1001
Opened 2022-04-07 13:16 UTC by khickey-newrelic

# Summary

Hey there - this is a quickstart dashboard to accompany the Customer experience quality foundation guide [here](https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide)

The json has been validated multiple times.  
The dashboard has been through the sanitize script. 
The information shared is in-line with the docs style guide. 
If anything is amiss, let me know how I can fix it!  

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots
![om-quality-foundation](https://user-images.githubusercontent.com/33837470/162206809-e3986c8e-a60a-4402-8310-32d4514d3179.png)

2022-04-08 18:56 UTC, josephgregoryii commented
Hey @khickey-newrelic  - just wanted to update and let you know we rolled out a change in our quickstarts configuration! Specifically, we are changing the `name` field in `config.yml` to `slug`. I would recommend checking out our [update to the contribution docs](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#slug--title-fields) for the changes. 😄

2022-04-08 22:47 UTC, aswanson-nr requested changes
Hey @khickey-newrelic! This is looking great, just noticed 2 small things that need to change and we should be good to merge

2022-04-08 22:47 UTC, aswanson-nr commented on quickstarts/oma-qf/config.yml
> +id:
Hey @khickey-newrelic! No need to have this field here, it will be autogenerated when it's merged!
```suggestion
```

2022-04-08 22:47 UTC, aswanson-nr commented on quickstarts/oma-qf/config.yml
> +name: customer-experience-quality-foundation
We recently put in a change to update this field name to be more accurately called `slug`. No changes needed other than renaming the field!
```suggestion
slug: customer-experience-quality-foundation 
```

2022-04-11 14:28 UTC, merged

2022-04-12 01:12 UTC, khickey-newrelic commented
Thanks for fixing the config for me @aswanson-nr!  I've been tied up at SKO - I was just about to make the fix when I saw you beat me to it.  :-)