WayScript Quickstart and Install Plan
newrelic/newrelic-quickstarts pull request #1036
Opened 2022-04-19 19:16 UTC by zstix

## Description

Adds the initial configuration for a WayScript quickstart and install plan. The primary install method (nerdlet) hasn't been created yet, so this will be in draft mode for now.

## Remaining Work

- [ ] Verify copy is correct
- [ ] Create install nerdlet (NR-1004)
- [ ] Update install plan to reference nerdlet ID

## Related Issue(s)

- NR-1362
- NR-1363

2022-04-19 19:47 UTC, louisleungk commented on quickstarts/wayscript/config.yml
> +  WayScript is an **Internal Developer Platform (IDP)** that enables scalable, single click development environments. The platform empowers early stage, high growth engineering teams with scalable, m
Can we keep the hyperlink within the body text and outside of the header?

2022-05-11 21:31 UTC, aswanson-nr commented on install/wayscript/install.yml
> +    nerdletId: todo-add-nerdlet-id
Just tossing a comment here so we don't forget to update this before merging.

2022-05-17 20:22 UTC, aswanson-nr commented on install/wayscript/install.yml
> +    nerdletId: todo-add-nerdlet-id
```suggestion
    nerdletId: external-install.install 
```

2022-05-18 22:47 UTC, merged

2022-05-18 22:51 UTC, josephgregoryii requested changes

2022-05-18 22:51 UTC, josephgregoryii commented on quickstarts/wayscript/config.yml
> +name: wayscript
```suggestion
slug: wayscript
```

2022-05-18 22:51 UTC, josephgregoryii commented on install/wayscript/install.yml
> +name: WayScript
```suggestion
displayName: WayScript
```

2022-05-18 22:51 UTC, josephgregoryii commented on install/wayscript/install.yml
> +    url: https://wsxdocs.wayscript.com/quickstart
https://github.com/newrelic/newrelic-quickstarts/blob/main/data-sources/argocd/config.yml#L8-L17

2022-05-18 22:51 UTC, josephgregoryii commented on install/wayscript/install.yml
> +name: WayScript
ignore this

2022-05-18 22:51 UTC, josephgregoryii commented on install/wayscript/install.yml
> +    url: https://wsxdocs.wayscript.com/quickstart
ignore this