chore: update lacework logo
newrelic/newrelic-quickstarts pull request #1041
Opened 2022-04-22 15:50 UTC by jcountsNR

updated lacework quickstart logo

2022-04-25 16:13 UTC, aswanson-nr requested changes
Hey @jcountsNR! Looks like there's a conflict in the config file. My suggested change should deal with it.

2022-04-25 16:13 UTC, aswanson-nr commented on quickstarts/lacework/config.yml
> +logo: logo.jpg
This is the cause of the conflict. We recently changed the name of this field over to `icon` to match our internal schema. Converting it over should resolve the issue.
```suggestion
icon: logo.jpg
```

2022-04-26 18:51 UTC, josephgregoryii approved these changes

2022-04-27 16:01 UTC, aswanson-nr approved these changes

2022-04-27 16:02 UTC, merged