First commit: New basic dashboard
newrelic/newrelic-quickstarts pull request #1059
Opened 2022-04-28 12:15 UTC by AstinCHOI

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-04-28 12:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1059) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1059) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1059) it.</sub>

2022-04-28 12:24 UTC, AstinCHOI commented
Hi NR quickstarts team,
This idea is from https://discuss.newrelic.com/t/apm-dashboards-for-basic-users/145305

2022-04-29 00:17 UTC, josephgregoryii approved these changes
Looks good!

2022-04-29 00:20 UTC, josephgregoryii commented
Since this is a new quickstart, i'll go ahead and tag @aswanson-nr to finalize the review.

2022-04-29 18:05 UTC, aswanson-nr commented
Hey @AstinCHOI! Thanks so much for this contribution! This is a great example of what's possible with dashboards. 
However, I'm not sure this will fill the expected use case because quickstart related dashboards are gated to full users within NR1. Knowing that, is this still something you would like to get into the quickstart ecosystem? /cc @zstix

2022-04-29 19:16 UTC, AstinCHOI commented
Hi @aswanson-nr, Basic users can use also these NRQLs that this dashboard used as well. Also, Full platform users can create this dashboard for basic users as well manually. I think there is nothing to be illegal things. 

Form this dashboard, all users will be curious of the kind of data such as APM, infra, browser, mobile, etc, so it could make increasing TDP. Basic users are still restricted from the trace data and the other curated dashboard. I would like to get in to the quickstart ecosystem. Could you please review this again?

2022-05-02 02:05 UTC, AstinCHOI commented
@aswanson-nr As you mentioned that "quickstart related dashboards are gated to full users within NR1.".
However, the dashboard created from a full platform user can be used by basic/core users in the NR1 dashboard menu and the customers I met use like that. 

I attached a video
(Left - **A full platform user** creates a dashboard from I/O)
(Right - **A basic user** sees the dashboard created by him)
https://drive.google.com/drive/folders/1dAfZf680V3O7uPAihyA98WX0mPeMc-WS

2022-05-03 19:28 UTC, aswanson-nr requested changes
Hey @AstinCHOI! Sorry for all the back and forth, just one last change and we should be good to merge.

2022-05-03 19:28 UTC, aswanson-nr commented on quickstarts/basic-dashboard/config.yml
> +id: e4abebd7-cce0-4474-b070-e2b0007f0e75
This will be auto generated after merging the pull request, please remove this field for now.
```suggestion
```

2022-05-03 20:18 UTC, AstinCHOI commented
Hey @aswanson-nr! Oh, okay. I just committed your last change. Thank you for your time and the review!

2022-05-03 20:51 UTC, aswanson-nr approved these changes

2022-05-03 20:51 UTC, merged