feat: add quickstart synthetics/private-locations
newrelic/newrelic-quickstarts pull request #1078
Opened 2022-05-09 02:05 UTC by keegoid-nr

# Summary

- add dashboard json
- add config.yml with descriptions
- add screenshots 800px wide
- fix broken script link in CONTRIBUTING.md
- fix some markdown linting errors in CONTRIBUTING.md

Not sure what to do about the install plan. Any help is appreciated.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

![synthetics-private-minions01](https://user-images.githubusercontent.com/61292402/167328257-895d8607-77da-436b-beee-69304678c1de.png)
![synthetics-private-minions02](https://user-images.githubusercontent.com/61292402/167328260-788aa3fa-fedc-45a2-a844-518a2d0a714f.png)
![synthetics-private-minions03](https://user-images.githubusercontent.com/61292402/167328262-bf1f43aa-474a-4ba0-be8e-38bcf97c5ea8.png)
![synthetics-private-minions04](https://user-images.githubusercontent.com/61292402/167328263-f18d5601-af46-4dcc-8515-8026e099c5f8.png)
![synthetics-private-minions05](https://user-images.githubusercontent.com/61292402/167328265-2297dcbf-bf45-4e70-801a-5ec20bda6a6d.png)

2022-05-09 18:21 UTC, josephgregoryii requested changes
Everything looks great, just need to remove one line in the `config.yml` file

2022-05-09 18:21 UTC, josephgregoryii commented on quickstarts/synthetics/private-locations/config.yml
> +id:
Hey @keegoid-nr  - We generate the ID automatically here after merging in a new quickstart:
https://github.com/newrelic/newrelic-quickstarts/blob/ed53333e26e9d8964fd3e245459f1c91d60fc0f3/utils/generate-uuids.js#L15-L20

We just need to remove this line from the config file. Other than that, everything looks great!

2022-05-10 16:19 UTC, aswanson-nr requested changes
Hey @keegoid-nr! Thanks so much for this contribution and the README updates!
I left a comment about adding an install plan, since you have a dashboard you'll need an install plan to make the quickstart "installable"

2022-06-01 18:49 UTC, keegoid-nr commented on quickstarts/synthetics/private-locations/config.yml
> +
Thanks @aswanson-nr, I added an install plan based on your advice. Let me know if you see any issues with it.

2022-06-07 23:31 UTC, aswanson-nr commented on quickstarts/synthetics/private-locations/dashboards/synthetics-private-minions/synthetics-private-minions.json
> +  "permissions": "PUBLIC_READ_WRITE",
Just need to remove this permissions field
```suggestion
```

2022-06-07 23:33 UTC, aswanson-nr approved these changes

2022-06-08 16:56 UTC, josephgregoryii approved these changes

2022-06-08 17:01 UTC, merged