feat: add quickstart akamai-datastream2
newrelic/newrelic-quickstarts pull request #1086
Opened 2022-05-12 10:32 UTC by gayatrisiva

# Summary

Submitting request for new quickstart for akamai-datastream2. Changes added:

- added dashboard json
- added config.yml with descriptions
- added dashboard screenshots
- added baseline alert definition

## Pre merge checklist

- [x] Did you check your NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

![datastream2-01](https://user-images.githubusercontent.com/104969649/168037449-7b5d8096-570a-44be-95fc-c86b764ba6a9.jpeg)
![datastream2-02](https://user-images.githubusercontent.com/104969649/168037478-475eabd2-9eb0-43a3-af73-97ef457e23ea.jpeg)
![datastream2-03](https://user-images.githubusercontent.com/104969649/168037485-dc58d749-396e-4067-aef4-92e2b6ef846c.jpeg)

2022-05-12 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1086) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1086) it.</sub>

2022-05-12 16:01 UTC, aswanson-nr requested changes
Thanks for your contribution, @gayatrisiva! This looks pretty much good to go, I just noticed one field that needs a name change.

2022-05-13 05:19 UTC, gayatrisiva commented on quickstarts/datastream2-akamai/config.yml
> +name: datastream2
Updated.

2022-05-13 05:19 UTC, gayatrisiva commented on quickstarts/datastream2-akamai/dashboards/datastream2/datastream2.json
> +  "permissions": "PUBLIC_READ_WRITE",
Updated.

2022-05-13 05:21 UTC, gayatrisiva commented on quickstarts/datastream2-akamai/config.yml
> +  - third-party-datastream
@aswanson-nr The install plan is currently a WIP from our end. We should have this ready for uploading logs to NewRelic soon and I shall update the link for the same when it is available.

2022-05-13 15:14 UTC, jcountsNR commented on quickstarts/datastream2-akamai/config.yml
> +  - third-party-datastream
@gayatrisiva , Sorry sounds like there is some confusion here. There is an install plan, and a data source which I believe you are confusing. The data source can be enhanced later, but an install plan
1. Install Plan - YML file that instructs I/O how to install your quickstart (housed in the install/third-party directory). You can look at the other files in the install/third-party dir for reference.
2. Data Source - a doc file guiding an end user on how to integrate your platform data with NR. We will probably build a doc file for this on our end once the quickstart is live.

2022-05-13 22:56 UTC, aswanson-nr approved these changes
@gayatrisiva, this looks good to go to me! We just need you to sign the Contributor License Agreement before we merge. Thanks for your contribution!

2022-05-16 15:57 UTC, merged