refactor(Contentsquare): Added install plans for contentsquare
newrelic/newrelic-quickstarts pull request #1148
Opened 2022-06-03 09:51 UTC by smamindla57

# Summary
Here for “Contentsquare quickstart” shows See Installation docs , so for that I have added install plans (third-party-contentsquare) then it can redirect to signup-page before seeing the installation docs. Added “ contentsquare” folder in third-party and also added install plans in contentsquare config.yml file.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

2022-06-03 21:30 UTC, josephgregoryii approved these changes

2022-06-03 21:33 UTC, josephgregoryii requested changes

2022-06-03 21:33 UTC, josephgregoryii commented on install/third-party/Contentsquare/install.yml
> +description:
```suggestion
description: |
```
Looks like we're just missing a multi-line indicator for the YAML file!

2022-06-06 18:07 UTC, aswanson-nr approved these changes

2022-06-06 18:08 UTC, merged