Added install plans for CloudFoundry
newrelic/newrelic-quickstarts pull request #1151
Opened 2022-06-03 10:27 UTC by vchandana25

# Summary

Here for “CloudFoundry quickstart” shows See Installation docs , so for that I have added install plans (third-party-cloudFoundry) then it can redirect to signup-page before seeing the installation docs. Added “cloudFoundry” folder in third-party and also added install plans in cloudFoundry config.yml file.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

2022-06-03 17:31 UTC, mickeyryan42 submitted a review, later dismissed

2022-06-03 21:22 UTC, josephgregoryii commented on install/third-party/cloudfoundry/install.yml
> +    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-tanzu-monitoring-integration
Hey @vchandana25 ! Just wanted to double check this is the correct URL - We have the same link for `vmware-tanzu` in a different PR 😄

2022-06-03 21:23 UTC, josephgregoryii requested changes
Just a quick question! Looks great 👍🏻

2022-06-03 21:23 UTC, josephgregoryii commented on install/third-party/cloudfoundry/install.yml
> +    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-tanzu-monitoring-integration
Hey @vchandana25 ! Just wanted to double check this is the correct URL - We have the same link for vmware-tanzu in a different PR 😄

2022-06-07 18:21 UTC, josephgregoryii approved these changes

2022-06-07 18:22 UTC, merged