refactor/NR-20915: vmware-esxi
newrelic/newrelic-quickstarts pull request #1155
Opened 2022-06-03 10:43 UTC by pkudikyala

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-06-03 21:10 UTC, josephgregoryii commented
hey @pkudikyala ! The PR looks great! One small thing - we prefer directory names remain consistent throughout the repository. 

Example: `quickstarts/vmware/vmware-esxi/`

If you wouldn't mind updating to reflect:
`install/third-party/VMware ESXi/` -> `install/third-party/vmware-esxi/`

Thanks!

2022-06-03 21:10 UTC, josephgregoryii requested changes
Comment above! 😄

2022-06-06 06:09 UTC, pkudikyala commented
Hi @josephgregoryii 
updated directory name, please once review it.

2022-06-06 18:14 UTC, aswanson-nr approved these changes

2022-06-06 18:17 UTC, merged