feat(pack): Added Azure MySQL quickstart
newrelic/newrelic-quickstarts pull request #1239
Opened 2022-06-10 09:21 UTC by EmilHammarstrand

# Summary

Added new quickstart with dashboard and alerts.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

![azure-mysql-db](https://user-images.githubusercontent.com/56023082/173034547-80dbeec9-80f9-4bab-83a0-77d3e2d22080.png)-

2022-06-13 17:21 UTC, aswanson-nr approved these changes

2022-06-13 17:23 UTC, aswanson-nr requested changes
Hey @EmilHammarstrand! This looks great, just one change needed around the dashboard directory.

2022-06-20 11:38 UTC, EmilHammarstrand commented
Hi @aswanson-nr!
Something like that? :)

2022-06-21 15:21 UTC, aswanson-nr approved these changes
@EmilHammarstrand Perfect!

2022-06-21 15:22 UTC, merged