NR-31194 NumPy integration
newrelic/newrelic-quickstarts pull request #1301
Opened 2022-07-29 06:36 UTC by pkosanam

# Summary

Ticket URL: https://issues.newrelic.com/browse/NR-31194

Description:

This PR has the new quickstart integration named "NumPy"

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-07-29 06:38 UTC, pkosanam commented
Here is the IO page preview:
![screencapture-newrelic-instant-observability-preview-2022-07-29-11_34_12](https://user-images.githubusercontent.com/99316285/181698362-dc79912c-a6ec-4eda-8d54-b0ddb45580e9.png)

2022-08-19 15:27 UTC, aswanson-nr commented
I'm assuming this one  is not stale!

2022-08-31 00:22 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  ## Comprehensive monitoring quickstart for NumPy
```suggestion
  ## Comprehensive quickstart for NumPy
```

2022-08-31 00:30 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  Monitor your NumPy applications, and analyze performance bottlenecks while operating in a live development environment.Full support for popular frameworks including Flask Visually monitor your web
```suggestion
With our NumPy integration, you can find and address performance bottlenecks while operating in a live development environment. Monitor your app via our dashboard quickstarts and ensure you're delivering the best user experience.
```

2022-08-31 00:30 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Reduce NumPy application downtime and detect the errors along with exceptions
```suggestion
  - Reduce NumPy application downtime and detect the errors and exceptions
```

2022-08-31 00:31 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Manage performance of homogeneous datasets and heterogeneous databases in context with your Numpy monitoring
```suggestion
  - Manage homogeneous and heterogeneous databases in context with your NumPy performance monitoring
```

2022-08-31 00:34 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Visually understand how a database is impacting your application
```suggestion
  - Get a visual overview of how a database affects your application
```

2022-08-31 00:35 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Assess the visibility of the underlying server infrastructure in relation to your Numpy monitoring
```suggestion
  - Assess the visibility of the underlying server infrastructure in relation to your NumPy monitoring
```

2022-08-31 00:37 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Alerts (Adpex score,WSGI Response, transaction error and Requests)
```suggestion
  - Alerts for Apdex score, WSGI response, transaction error, and requests
```

2022-08-31 00:37 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Easy to use Dashboards (most popular transactions, average transaction duration today compared with that for the previous week, Apdex score comparisons, and more)
```suggestion
  - Easy to use dashboards, including most popular transactions, average transaction duration over time, Apdex score comparisons, and more)
```

2022-08-31 00:38 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Monitor NumPy Elements and functions
```suggestion
  - Monitor NumPy elements and functions
```

2022-08-31 00:38 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  - Understand infrastructure resource consumption of application performance
```suggestion
  - Understand infrastructure resource consumption
```

2022-08-31 00:40 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  Get a comprehensive understanding of performance with customized dashboards including total requests, total logins, web transactions, and more with New Relic’s NumPy monitoring tool.
```suggestion
  Get a comprehensive overview of your NumPy app's performance with customized dashboards. Track total requests, total logins, web transactions, and more with New Relic’s NumPy monitoring tool.
```

2022-08-31 00:46 UTC, akristen commented on quickstarts/python/numpy/config.yml
> +  ## Comprehensive monitoring quickstart for NumPy
```suggestion
  ## Quickstart for comprehensive monitoring with NumPy
```

2022-08-31 16:29 UTC, aswanson-nr requested changes
Looking like we just need to clean up some of the dashboard NRQL queries

2022-08-31 16:29 UTC, aswanson-nr commented on dashboards/numpy/numpy.json
> +{
Let's get the entity GUIDs and explicit times ranges removed from this dashboard!

2022-09-12 06:59 UTC, pkosanam commented
closing this PR as this quickstart is not present in our current release

2022-09-12 06:59 UTC, closed without merging