NR-31187 Typescript Integration
newrelic/newrelic-quickstarts pull request #1316
Opened 2022-08-15 00:53 UTC by pkosanam

# Summary
Ticket URL: https://issues.newrelic.com/browse/NR-31187
Description: 
This PR has the new quickstart integration named "Typescript"

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

# Preview:
![screencapture-newrelic-instant-observability-preview-2022-08-15-06_18_23](https://user-images.githubusercontent.com/99316285/184561641-3bbef168-2bd4-4ee5-8e17-845ed9781119.png)

2022-08-31 00:46 UTC, akristen commented on quickstarts/node-js/typescript/config.yml
> +  ## Comprehensive monitoring quickstart for TypeScript
```suggestion
  ## Quickstart for comprehensive monitoring with TypeScript
```

2022-08-31 16:17 UTC, aswanson-nr requested changes
Quickstart looks good! However, seeing lots of unique GUIDs in the dashboard NRQL queries. Let's get those cleaned up before we merge.

2022-08-31 16:17 UTC, aswanson-nr commented on dashboards/typescript/typescript.json
> +{
I'm seeing a lot of entity GUIDs and explicit time ranges in these NRQL queries. Let's get this updated to handling entities with different GUIDs and remove the explicit time ranges.

2022-09-14 15:38 UTC, pkosanam commented
Closing this PR as we have created a new PR related to typescript: https://github.com/newrelic/newrelic-quickstarts/pull/1356

2022-09-14 15:38 UTC, closed without merging