Csharp new int
newrelic/newrelic-quickstarts pull request #1357
Opened 2022-09-14 11:27 UTC by dikshab0202

Ticket: https://issues.newrelic.com/browse/NR-31202 
Description: This PR has the new quickstart integration named "C#"
![c#](https://user-images.githubusercontent.com/101187392/190141705-03c15d95-f102-4906-91ea-8a9a20299f78.png)

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-09-14 15:48 UTC, pkosanam commented
@akristen , Request you to kindly review the content in this PR, so that we can update this PR with it.

2022-09-14 15:55 UTC, pkosanam requested changes

2022-09-14 15:55 UTC, pkosanam commented on quickstarts/dotnet/csharp/config.yml
> +    url: https://docs.newrelic.com/docs/agents/net-agent/getting-started/compatibility-requirements-net-framework-agent
Hi @akristen , request you to kindly provide us the right docs url, so that we can update this PR with it. 😃

2022-09-14 16:30 UTC, seemantk commented
Can you also please add the C# logo to the public I/O page for this?

https://commons.wikimedia.org/wiki/File:Csharp_Logo.png

2022-09-14 21:38 UTC, dikshab0202 commented
> Can you also please add the C# logo to the public I/O page for this?
> 
> https://commons.wikimedia.org/wiki/File:Csharp_Logo.png

Hi @seemantk , logo has been updated now. Thank you..

2022-09-15 10:32 UTC, pkosanam requested changes

2022-09-15 10:32 UTC, pkosanam commented on quickstarts/dotnet/csharp/config.yml
> +slug: csharp
please change the slug to "c-sharp"

2022-09-15 10:32 UTC, pkosanam commented on quickstarts/dotnet/csharp/config.yml
> +  - c sharp
please add please add C# also in keywords section

2022-09-15 10:32 UTC, pkosanam commented on quickstarts/dotnet/csharp/config.yml
> +  - most popular
Please remove "most popular" as C# is not part of most popular list yet

2022-09-20 15:46 UTC, aswanson-nr requested changes
Looking good, but link updates are needed!

2022-09-21 06:08 UTC, dikshab0202 commented on quickstarts/dotnet/csharp/config.yml
> +    url: https://newrelic.slack.com/archives/C03TNQ8F59C/p1663628343490579?thread_ts=1663628135.825509&cid=C03TNQ8F59C
Hi @aswanson-nr , I have replaced the doc url with this one -> https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework#technologies . Thank you..

2022-09-21 17:27 UTC, pkosanam approved these changes

2022-09-22 15:57 UTC, akristen commented on quickstarts/dotnet/csharp/config.yml
> +  - See the filename and line number of the C# stack trace so you never have to guess. To reduce noise, logically filter and aggregate C# exceptions.
```suggestion
  - See the filename and line number from the C# stack trace so you never have to guess. To reduce noise, logically filter and aggregate C# exceptions.
```

2022-09-22 16:03 UTC, akristen commented on quickstarts/dotnet/csharp/config.yml
> +  - Get a bird's eye view of your C# applications using New Relic’s dashboard and get meaningful data about C# errors
```suggestion
  - Get meaningful data about C# error from your dashboard```

2022-09-22 16:45 UTC, akristen commented on quickstarts/dotnet/csharp/config.yml
> +  ## Get end-to-end visibility into your C# operation terrain and all the dependencies
```suggestion
  ## End-to-end visibility into your C# operations
```

2022-09-22 16:52 UTC, akristen commented on quickstarts/dotnet/csharp/config.yml
> +  Automatically discover operation topology and interdependencies, relate and trace crucial business deals grounded on product operation address feature and prioritize the end-to-end business deals p
```suggestion
Our C# dashboard translates your ingested data into a map that lets you trace business transactions across your C# stack. See your performance errors in context and prioritize your most critical operations. ```

2022-09-22 16:53 UTC, akristen approved these changes
Please approve or reject the changes I have made. Good to merge!

2022-09-23 09:55 UTC, dikshab0202 commented
> Please approve or reject the changes I have made. Good to merge!

Thank you @akristen

2022-09-23 20:22 UTC, aswanson-nr approved these changes
Looks good from my perspective! @pkosanam, is this good to merge?

2022-09-26 06:42 UTC, pkosanam commented
> Looks good from my perspective! @pkosanam, is this good to merge?

Sure @aswanson-nr, looks good for me too.. 👍

2022-09-26 16:16 UTC, merged