System manager distributor
newrelic/newrelic-quickstarts pull request #1360
Opened 2022-09-15 17:27 UTC by 4demos

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-09-15 21:20 UTC, josephgregoryii reviewed
Hey @4demos - Couple comments below. 

Also we wanted to call out that since this quickstart does not have any dashboards, alerts, or install plans, this quickstart page will only lead them to the docs page, where in this case would be a broken link.

2022-09-15 21:20 UTC, josephgregoryii commented on quickstarts/aws/aws-smd/config.yml
> +  Check out the [documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-system-manager-distributor) to learn
Hey @4demos - looks like this link doesn't exist or might be incorrect. Would you mind double checking the link?

2022-09-15 21:20 UTC, josephgregoryii commented on quickstarts/aws/aws-smd/config.yml
> +      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-system-manager-distributor
Same url here as well

2022-09-16 16:51 UTC, 4demos commented on quickstarts/aws/aws-smd/config.yml
> +      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-system-manager-distributor
URL has been updated

2022-09-20 15:58 UTC, aswanson-nr requested changes
I found a few issues with the description and summary, mostly content related. Probably just need to reword them a little. 
I also noticed that this quickstart does not include any dashboards or alerts, meaning that all this will do is link user's out to the link in the `documentation` field. We generally try to include some extra value for users, so that there's a reason to get started using the quickstart. Are there any dashboards we can provide that display the data generated by this integration?

2022-09-20 15:58 UTC, aswanson-nr commented on quickstarts/aws/aws-smd/config.yml
> +  Use New-Relic-infrastructure-monitoring-agent tile to install the agent and monitor your EC2 instances with New Relic
The wording here is a little suspect, I don't think user's will understand what a "tile" is, I'm not quite sure myself. If it's referring to the "tile" in the IO catalogue page view, then we definitely don't want to refer to it that way. I'd like to get this updated before we publish it.

2022-09-20 15:58 UTC, aswanson-nr commented on quickstarts/aws/aws-smd/config.yml
> +  more about New Relic monitoring and integration with AWS System Manager Distributor.
I think we could get a little more information in here before tossing the user out to the docs site. We want users to understand the value provided by this quickstart before they need to open links to other pages.

2022-09-20 16:21 UTC, seemantk commented
Let's park this PR until @4demos and I sync up on this effort

2022-09-23 20:24 UTC, aswanson-nr commented
Moving this to draft until it is ready for review

2022-11-08 02:14 UTC, closed without merging