NR-34617: Added new quickstart- ADO.NET
newrelic/newrelic-quickstarts pull request #1376
Opened 2022-09-23 11:49 UTC by dikshab0202

Ticket: https://issues.newrelic.com/browse/NR-34617 
Description: This PR has the new quickstart integration named "Ado.net"

![image](https://user-images.githubusercontent.com/101187392/191954022-0ee81b02-e495-4b5d-8d7d-6196bf5f5484.png)

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-09-23 12:55 UTC, pkosanam requested changes

2022-09-23 12:55 UTC, pkosanam commented on dashboards/ado-dotnet/ado-dotnet.json
> +  "name": "Dotnet - with c# & ado.net",
Please change this to "ADO.NET"

2022-09-23 12:59 UTC, pkosanam commented
Hi @akristen , Here is the new quickstart integration of ADO.NET
Requesting your review on this IO page content
Thank you
cc: @mdumpati

2022-09-23 21:10 UTC, aswanson-nr commented
Hey all, just going to mark this as a draft since it is still waiting on content feedback. Just don't want it to get merged accidentally.

2022-09-24 21:42 UTC, raahulbasu commented
1. Add a full stop symbol for each bullet points mentioned under 'why monitor ADO.NET' and 'what's included in this quickstart'
2. Under what's included in this quickstart, bullet point #2 add appropriate spaces, uppercase/lowercase for metric names i.e., HardConnectsPerSecond, HardDisconnectsPerSecond etc.

2022-09-30 15:04 UTC, akristen commented on quickstarts/dotnet/ado-dotnet/config.yml
> +    - Alerts (High load connection, Hard connects exceeding max limit, Pool size exceeding optimum limit).
```suggestion
    - Alerts (high load connection, hard connects exceeding max limit, pool size exceeding optimum limit).
```

2022-09-30 15:05 UTC, akristen commented on quickstarts/dotnet/ado-dotnet/config.yml
> +    - Dashboards (Hard connects per second, Hard disconnects per second, Number of active connections, Soft connects per second,  and more).
```suggestion
    - Dashboards (hard connects per second, hard disconnects per second, number of active connections, soft connects per second,  and more).
```

2022-09-30 15:06 UTC, akristen commented on quickstarts/dotnet/ado-dotnet/config.yml
> +  Discover more about ADO.NET, the importance of New Relic's ADO.NET quickstart, the advantages of ADO.NET monitoring, and the best features to look for in this quickstart.
```suggestion
  Discover how the ADO.net quickstart gives you an advantage with comprehensive monitoring capabilities.
```

2022-10-03 06:12 UTC, pkosanam requested changes

2022-10-03 06:12 UTC, pkosanam commented on quickstarts/dotnet/ado-dotnet/config.yml
> +    - Dashboards (hard connects per second, hard disconnects per second, number of active connections, soft connects per second,  and more).
Observed extra space after "second,"

I feel, text need to be like below:
Dashboards (hard connects per second, hard disconnects per second, number of active connections, soft connects per second and more).

2022-10-03 13:11 UTC, pkosanam requested changes

2022-10-03 13:11 UTC, pkosanam commented on quickstarts/dotnet/ado-dotnet/config.yml
> +  ## Comprehensive monitoring quickstart for ADO.net
Should this be ADO.net or ADO.NET ?

2022-10-03 13:11 UTC, pkosanam commented on quickstarts/dotnet/ado-dotnet/config.yml
> +  When you monitor ADO.net with New Relic, you can observe your ADO.NET data set in real time. Our .NET agent will also let you correlate transactions moving across your application environment and t
Should this be ADO.net or ADO.NET ?

2022-10-03 13:11 UTC, pkosanam commented on quickstarts/dotnet/ado-dotnet/config.yml
> +  Discover how the ADO.net quickstart gives you an advantage with comprehensive monitoring capabilities.
Should this be ADO.net or ADO.NET ?

2022-10-03 13:34 UTC, pkosanam approved these changes

2022-10-03 13:34 UTC, pkosanam approved these changes
looks good

2022-10-04 17:10 UTC, aswanson-nr approved these changes

2022-10-04 17:11 UTC, merged