Quickstart for Jenkins-Prometheus
newrelic/newrelic-quickstarts pull request #1386
Opened 2022-09-27 18:14 UTC by k1nect

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

## Pre merge checklist

- [✔️] Did you check you NRQL syntax? - Does it work?
- [✔️] Did you include an InstallPlan and Documentation reference?
- [✔️] Are all documentation links publically accessible?
- [✔️] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [✔️] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [✔️] Does the PR contain a screenshot for each of your dashboards?
- [✔️] Do your screenshots show data?
- [✔️] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [✔️] Did you check that your alerts actually work?

2022-09-27 18:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1386) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1386) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1386) it.</sub>

2022-09-28 20:49 UTC, aswanson-nr requested changes
Hey @k1nect! This looks great, just need to remove that id value on the quickstart config!

2022-09-28 20:49 UTC, aswanson-nr commented on quickstarts/jenkins-prometheus/config.yml
> +id: 980ab07a-3483-4b44-bbac-ed9c0a9a41a1
The system will automatically generate an id for new quickstarts, please remove this line
```suggestion
id: 980ab07a-3483-4b44-bbac-ed9c0a9a41a1
```

2022-09-29 04:55 UTC, k1nect commented
> Hey @k1nect! This looks great, just need to remove that id value on the quickstart config!

@aswanson-nr Implemented comment -->removed this id line. Thank you for review and feedback.

2022-09-30 16:21 UTC, zstix approved these changes

2022-09-30 16:22 UTC, mickeyryan42 approved these changes

2022-10-04 16:52 UTC, aswanson-nr approved these changes

2022-10-04 16:54 UTC, merged