Quickstart for InfluxDB
newrelic/newrelic-quickstarts pull request #1392
Opened 2022-09-29 21:23 UTC by k1nect

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

## Pre merge checklist

- [✔️] Did you check you NRQL syntax? - Does it work?
- [✔️] Did you include an InstallPlan and Documentation reference?
- [✔️] Are all documentation links publically accessible?
- [✔️] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [✔️] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [✔️] Does the PR contain a screenshot for each of your dashboards?
- [✔️] Do your screenshots show data?
- [✔️] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [✔️] Did you check that your alerts actually work?

2022-09-30 16:19 UTC, zstix requested changes
One minor tweak needed in the yaml config file.

2022-09-30 16:19 UTC, zstix commented on quickstarts/ext-influxdb/config.yml
> + # InfluxDB quickstart highlights
It looks like this is missing a space to align the indentation with the next line. This is causing the yaml to be invalid.
```suggestion
  # InfluxDB quickstart highlights
```

2022-10-04 14:20 UTC, mickeyryan42 approved these changes

2022-10-04 16:59 UTC, zstix approved these changes

2022-10-04 17:01 UTC, merged