feat(flashdb): Added a quickstart for flashdb
newrelic/newrelic-quickstarts pull request #1401
Opened 2022-10-02 23:34 UTC by mehreentahir16

feat(flashdb): Added a quickstart for flashdb

# Summary

This is a demo quickstart for the quickstart course.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Are all documentation links publically accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [ ] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2022-10-05 16:10 UTC, jcountsNR commented
@mehreentahir16 , is this an actual quickstart that we are wanting to merge or is this testing from the docs example only?

2022-10-06 16:09 UTC, aswanson-nr requested changes
Hey @mehreentahir16, I found a few things that need to get cleaned up. If I jumped on this PR to early and it's still in development, please mark it has "draft" until it is ready to be reviewed and merged.

2022-10-06 16:09 UTC, aswanson-nr commented on data-sources/flashdb/config.yml
> +id: FlashDB
This should be lowercase
```suggestion
id: flashdb
```

2022-10-07 10:34 UTC, mehreentahir16 commented
@aswanson-nr @jcountsNR This is just a demo PR for the quickstart course. Please do not merge but I had to go through the review process to make sure I'm not missing steps. I'll fix the PR for you to review it one more time and then update the course based on the process. Thanks

2022-10-07 10:35 UTC, mehreentahir16 commented on quickstarts/flashdb/config.yml
> +    url: https://developer.newrelic.com/contribute-to-quickstarts
The only related resources for this quickstart is the course since it's just a demo.

2022-10-07 15:57 UTC, aswanson-nr commented
@mehreentahir16 Gotcha! I'm just going to put it in draft to ensure it doesn't get merged, all the workflows and checks will still run as usual!

2022-10-10 10:16 UTC, mehreentahir16 commented
@aswanson-nr I committed the changes but I still don't see alerts. Can you please check?

2022-10-12 15:35 UTC, aswanson-nr commented on quickstarts/flashdb/config.yml
> +alerts:
Hey @mehreentahir16! This is why they aren't showing up in the preview!
```suggestion
alertPolicies:
```

2022-11-28 02:05 UTC, closed without merging