Added skykit to the quickstart folder
newrelic/newrelic-quickstarts pull request #1420
Opened 2022-10-07 19:46 UTC by marty733

# Summary

Adding Skykit to the quickstart folder. This quickstart does not have any components that will live within the New Relic software, it will only be on the marketing site. 

Note: review support Level, marked as verified per discussion with New Relic. 

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Are all documentation links publically accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [x] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [x] Did you check that your alerts actually work?

2022-10-07 19:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1420) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1420) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1420) it.</sub>

2022-10-10 16:17 UTC, jcountsNR requested changes
I only saw one small issue with the URL, the rest looks good. I might defer to the review team on the language here and whether or not this would qualify as 'verified'.

2022-10-10 16:17 UTC, jcountsNR commented on quickstarts/skykit/config.yml
> +website: https://www.skykit.com/products/dashboards/connections/new-relic/
```suggestion
website: https://www.skykit.com
```

This should just be the company site, you can leave the documentation link in the doc references.

2022-10-10 17:03 UTC, jcountsNR commented
@marty733 , looks like you have not signed the contributor license agreement. Can you take a look above?

2022-10-10 23:22 UTC, marty733 commented
@jcountsNR Signed the CLA, let me know what else I can do to help!

2022-10-11 18:12 UTC, jcountsNR approved these changes

2022-10-12 00:02 UTC, merged