Nr 49260 quick start alerts nginx-ingress
newrelic/newrelic-quickstarts pull request #1436
Opened 2022-10-17 07:20 UTC by gsidhwani-nr

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

## Pre merge checklist

- [X ] Did you check you NRQL syntax? - Does it work?
- [ X] Did you include an InstallPlan and Documentation reference?
- [X ] Are all documentation links publically accessible?
- [ X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [ X] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [ X] Does the PR contain a screenshot for each of your dashboards?
- [X ] Do your screenshots show data?
- [ X] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [X ] Did you check that your alerts actually work?

2022-10-17 17:17 UTC, aswanson-nr commented
Hey again @gsidhwani-nr, we now have a ticket on the backlog to get validation updated to allow for these new `operator` terms. If you'd like to get this merged in before we can get that updated, swapping to a `ABOVE` or `BELOW` value should get you most of the way there!

2022-10-17 17:26 UTC, gsidhwani-nr commented
Updated to BELOW as suggested.

On Mon, Oct 17, 2022 at 10:47 PM Alec Swanson ***@***.***>
wrote:

> Hey again @gsidhwani-nr <https://github.com/gsidhwani-nr>, we now have a
> ticket on the backlog to get validation updated to allow for these new
> operator terms. If you'd like to get this merged in before we can get
> that updated, swapping to a ABOVE or BELOW value should get you most of
> the way there!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/newrelic/newrelic-quickstarts/pull/1436#issuecomment-1281195516>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A267V3LUXAG7XACQLURGQLTWDWC4BANCNFSM6AAAAAARGYPC6Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-18 15:26 UTC, aswanson-nr commented on alert-policies/nginx-ingress/Ingress-certificate-expiry-alert.yml
> +    operator: BELOW_OR_EQUALS
Found one more `BELOW_OR_EQUALS`!

2022-10-18 15:29 UTC, gsidhwani-nr commented
Fixed with BELOW.

On Tue, Oct 18, 2022 at 8:56 PM Alec Swanson ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In alert-policies/nginx-ingress/Ingress-certificate-expiry-alert.yml
> <https://github.com/newrelic/newrelic-quickstarts/pull/1436#discussion_r998393626>
> :
>
> > +name: Ingress certificate expiry alert
> +
> +description: |+
> + This alert is triggered when there are only 15 or fewer days remaining for certificate expiration. This alert may be further configured as per desired expiration alert requirements.
> +type: STATIC
> +nrql:
> +  query: "FROM Metric SELECT floor((latest(nginx_ingress_controller_ssl_expire_time_seconds) - (aggregationendtime()/1000)) / (24*60*60)) FACET host WHERE instrumentation.name = 'remote-write'"
> +
> +# Function used to aggregate the NRQL query value(s) for comparison to the terms.threshold (Default: SINGLE_VALUE)
> +valueFunction: SINGLE_VALUE
> +
> +# List of Critical and Warning thresholds for the condition
> +terms:
> +  - priority: CRITICAL
> +    # Operator used to compare against the threshold.
> +    operator: BELOW_OR_EQUALS
>
> Found one more BELOW_OR_EQUALS!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/newrelic/newrelic-quickstarts/pull/1436#pullrequestreview-1146058248>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A267V3JTBFPGWQ6K7EFDOZTWD26SRANCNFSM6AAAAAARGYPC6Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-18 16:16 UTC, thezackm requested changes
@gsidhwani-nr - added some comments on formatting changes requested as part of the `prometheus-growth-hack` initiative

@aswanson-nr - curious if you have any opinions about the note on `histogrampercentile()` vs `bucketpercentile()` in the `P99-latency-alert.yml` condition.

2022-10-18 16:16 UTC, thezackm commented on alert-policies/nginx-ingress/High-http-4xx-5xx-error-alert.yml
> + This alert is triggered when the http request success rate drops below 95 percent. This alert may be further configured as per the desired success percentage requirements.
recommend updating for clarity and updating the `HTTP` initialism:

>This alert is triggered when the HTTP request success rate drops below 95 percent. The alert threshold can be changed to your desired success percentage requirements.

2022-10-18 16:16 UTC, thezackm commented on alert-policies/nginx-ingress/Ingress-certificate-expiry-alert.yml
> +name: Ingress certificate expiry alert
recc: change `expiry` to `expiration`

2022-10-18 17:44 UTC, aswanson-nr commented on alert-policies/nginx-ingress/P99-latency-alert.yml
> +  query: "SELECT histogrampercentile(nginx_ingress_controller_request_duration_seconds_bucket, (100 * 0.99))*1000 FROM Metric"
Hey @thezackm, I'm always for avoiding deprecated functions!

2022-10-19 08:28 UTC, gsidhwani-nr commented
Implemented feedback !

On Tue, Oct 18, 2022 at 11:14 PM Alec Swanson ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In alert-policies/nginx-ingress/P99-latency-alert.yml
> <https://github.com/newrelic/newrelic-quickstarts/pull/1436#discussion_r998538328>
> :
>
> > @@ -0,0 +1,26 @@
> +name: P99 latency alert
> +
> +description: |+
> + This alert is triggered when there is a latency in processing a request that is more than 100 milliseconds for the 99th percentile of request volume. This sample alert may be further configured as per desired latency requirements.
> +type: STATIC
> +nrql:
> +  query: "SELECT histogrampercentile(nginx_ingress_controller_request_duration_seconds_bucket, (100 * 0.99))*1000 FROM Metric"
>
> Hey @thezackm <https://github.com/thezackm>, I'm always for avoiding
> deprecated functions!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/newrelic/newrelic-quickstarts/pull/1436#discussion_r998538328>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A267V3LOQBFH5VJF7XH7JXLWD3OYTANCNFSM6AAAAAARGYPC6Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-20 07:22 UTC, gsidhwani-nr commented on alert-policies/nginx-ingress/Ingress-certificate-expiry-alert.yml
> +    operator: BELOW_OR_EQUALS
Updated

2022-10-20 07:22 UTC, gsidhwani-nr commented on alert-policies/nginx-ingress/High-http-4xx-5xx-error-alert.yml
> +name: High http 4xx/5xx error alert
updated

2022-10-20 07:22 UTC, gsidhwani-nr commented on alert-policies/nginx-ingress/High-http-4xx-5xx-error-alert.yml
> + This alert is triggered when the http request success rate drops below 95 percent. The alert threshold can be changed to your desired latency alerting requirements.
updated

2022-10-20 07:24 UTC, gsidhwani-nr commented on alert-policies/nginx-ingress/P99-latency-alert.yml
> +  query: "SELECT bucketpercentile(nginx_ingress_controller_request_duration_seconds_bucket, (100 * 0.99))*1000 FROM Metric"
Updated as suggested. Also updated the description field.

2022-10-20 17:31 UTC, thezackm requested changes
@gsidhwani-nr - one small typo change and this one is good to go; thanks for all the work on this!

2022-10-20 17:31 UTC, thezackm commented on alert-policies/nginx-ingress/High-http-4xx-5xx-error-alert.yml
> + This alert is triggered when the HTTP request success rate drops below 95 percent. The alert threshold can be changed to your desired latency alerting requirements.
small typo here: 
```
desired latency alerting requirements
```

this is an error alert, should be something more like:
```
desired error alerting requirements
```

2022-10-20 17:49 UTC, gsidhwani-nr commented
Applied the changes !

On Thu, Oct 20, 2022 at 11:01 PM Zack Mutchler ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @gsidhwani-nr <https://github.com/gsidhwani-nr> - one small typo change
> and this one is good to go; thanks for all the work on this!
> ------------------------------
>
> In alert-policies/nginx-ingress/High-http-4xx-5xx-error-alert.yml
> <https://github.com/newrelic/newrelic-quickstarts/pull/1436#discussion_r1000923832>
> :
>
> > @@ -0,0 +1,34 @@
> +name: High HTTP 4xx/5xx error alert
> +
> +description: |+
> + This alert is triggered when the HTTP request success rate drops below 95 percent. The alert threshold can be changed to your desired latency alerting requirements.
>
> small typo here:
>
> desired latency alerting requirements
>
> this is an error alert, should be something more like:
>
> desired error alerting requirements
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/newrelic/newrelic-quickstarts/pull/1436#pullrequestreview-1149684913>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A267V3MTY6VHGFVUYQT3HXLWEF6YVANCNFSM6AAAAAARGYPC6Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-21 14:01 UTC, thezackm approved these changes
approved for the `prometheus-growth` project; thanks @gsidhwani-nr!

2022-10-21 15:52 UTC, aswanson-nr approved these changes

2022-10-21 16:10 UTC, merged