Nr 54707 cockroach db quick start alerts
newrelic/newrelic-quickstarts pull request #1488
Opened 2022-11-03 15:39 UTC by gsidhwani-nr

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

## Pre merge checklist

- [ X] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Are all documentation links publically accessible?
- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [X ] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [X] Did you check that your alerts actually work?

https://staging.onenr.io/0gbRK6OBOwE

2022-11-03 17:46 UTC, thezackm requested changes
@gsidhwani-nr - review submitted for `prometheus-growth` project.

this PR needs to be combined with PR #1491 and you need to add a `/quickstarts/cockroach-db/config.yml` file and associated logo file that references both the alerts and dashboard.

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/Low_disk_storage.yml
> +  Send an alert when storage capacity is available below 15% .The alert threshold can be changed to your desired storage limit requirements.
please update for readability: 

```
Send an alert when available storage capacity is below 15% for over 15 minutes. The alert threshold can be changed to your desired storage limit requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/ca_certificate expiration.yml
> +  This alert is triggered when there are less than 90 days remaining for certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
please update for readability: 

```
This alert is triggered when there are less than 90 days remaining for CA certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/client_ca_certificate expiration.yml
> +  This alert is triggered when there are less than 90 days remaining for certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
please update for readability: 

```
This alert is triggered when there are less than 90 days remaining for Client CA certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/node_certificate expiration.yml
> +  This alert is triggered when there are less than 30 days remaining for certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
please update for readability: 

```
This alert is triggered when there are less than 30 days remaining for Node certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/ui_ca_certificate expiration.yml
> +  This alert is triggered when there are less than 90 days remaining for certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
please update for readability: 

```
This alert is triggered when there are less than 90 days remaining for UI CA certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/ui_certificate expiration.yml
> +  This alert is triggered when there are less than 30 days remaining for certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
please update for readability: 

```
This alert is triggered when there are less than 30 days remaining for UI certificate expiration. The alert threshold can be changed to your desired expiration alerting requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/cluster_running_with_different_versions.yml
> +  Send an alert Cluster running with different versions of cockroachDB .
please update for readability: 

```
This alert is triggered when there are multiple versions of CockroachDB running in a single cluster.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/high_fd_open_count.yml
> +  Send an alert when a node is getting 80% of the open file descriptor limit.The alert threshold can be changed to your desired fd limit requirements.
please update for readability: 

```
This alert is triggered when a node passes 80% of the open file descriptors limit for 15 minutes. The alert threshold can be changes to your desired file descriptors limit requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/instance_dead.yml
> +  Send an alert when an instance is down for 15 minutes. The alert threshold can be changed to your acceptable downtime requirements.
please update for readability: 

```
This alert triggers when an instance is down for 15 minutes. The alert threshold can be changed to your acceptable downtime requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/node_down.yml
> +name: node down alert
change to `Node down alert` (sentence case)

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/node_down.yml
> +  Send an alert when an node is down for 15 minutes. The alert threshold can be changed to your acceptable downtime requirements.
please update for readability: 

```
This alert triggers when a node is down for 15 minutes. The alert threshold can be changed to your acceptable downtime requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_latch_requests.yml
> +name: Slow lease requests
change to `Slow latch requests` (to match correct metric in the alert)

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_latch_requests.yml
> +    operator: EQUALS
this should be `ABOVE`

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_latch_requests.yml
> +    threshold: 1
this should be `0`

(alert me when > 0)

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_lease_requests.yml
> +  Slow lease requests
please update for readability: 

```
This alert triggers when there are > 0 slow lease requests for over 5 minutes. The alert threshold can be changed to your acceptable slow request requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_lease_requests.yml
> +    operator: EQUALS
this should be `ABOVE`

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_lease_requests.yml
> +    threshold: 1
this should be `0`

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_raft_requests.yml
> +  Slow raft requests
please update for readability: 

```
This alert triggers when there are > 0 slow raft requests for over 5 minutes. The alert threshold can be changed to your acceptable slow request requirements.
```

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_raft_requests.yml
> +    operator: EQUALS
this should be `ABOVE`

2022-11-03 17:46 UTC, thezackm commented on alert-policies/cockroach-db/slow_raft_requests.yml
> +    threshold: 1
this should be `0`

2022-11-04 14:13 UTC, thezackm submitted a review, later dismissed
approved for `prometheus-growth` project; thanks!

2022-11-04 16:47 UTC, zstix approved these changes

2022-11-04 16:50 UTC, zstix requested changes

2022-11-04 16:50 UTC, zstix commented on quickstarts/cockroach-db/config.yml
> +slug: cockroach database-newrelic
The slug can only have letters, numbers, and hyphens. Perhaps we should use this instead:

```suggestion
slug: cockroach-database-newrelic
```

2022-11-05 04:16 UTC, gsidhwani-nr commented
changes done. cockroach-database-newrelic


On Fri, Nov 4, 2022 at 10:20 PM Zack Stickles ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In quickstarts/cockroach-db/config.yml
> <https://github.com/newrelic/newrelic-quickstarts/pull/1488#discussion_r1014258651>
> :
>
> > @@ -0,0 +1,48 @@
>
> +id: e2ee8b6e-5c2a-11ed-9b6a-0242ac120002
>
> +slug: cockroach database-newrelic
>
>
> The slug can only have letters, numbers, and hyphens. Perhaps we should
> use this instead:
> ⬇️ Suggested change
>
> -slug: cockroach database-newrelic
>
> +slug: cockroach-database-newrelic
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/newrelic/newrelic-quickstarts/pull/1488#pullrequestreview-1168888141>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A267V3NYQHGNRK3P7IAZ3ALWGU5FXANCNFSM6AAAAAARWIWLHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-08 11:03 UTC, zstix approved these changes

2022-11-08 11:11 UTC, merged