NR-80059-MERN-stack-integration
newrelic/newrelic-quickstarts pull request #1597
Opened 2023-01-14 11:41 UTC by pkosanam

JIRA Ticket: https://issues.newrelic.com/browse/NR-80059

Description:
This code change includes below quickstart pages
1. MERN stack
2. ReactJS

Preview:
1. MERN stack:
![mern-preview](https://user-images.githubusercontent.com/99316285/212470047-e778e06c-0d47-4ec3-89ae-695d37848259.png)

2. ReactJS:
![reactjs-preview](https://user-images.githubusercontent.com/99316285/212470085-14ed71c8-40e2-41f6-9cf5-eb5d20cd3406.png)

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Are all documentation links publically accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [ ] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-02-16 18:46 UTC, brammerl commented
Hello, We are no longer accepting install plans as a part of the quickstart schema. We are instead moving to use data sources. You can either refer to an [already existing data source](https://github.com/newrelic/newrelic-quickstarts/tree/main/data-sources) in this repository or[ make your own](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#data-sources-1) community data source. 

If this applies to your PR, please make the proper update to your quickstart's config to reference only data sources.

2023-02-17 09:58 UTC, pkosanam commented
> Hello, We are no longer accepting install plans as a part of the quickstart schema. We are instead moving to use data sources. You can either refer to an [already existing data source](https://github.com/newrelic/newrelic-quickstarts/tree/main/data-sources) in this repository or[ make your own](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#data-sources-1) community data source.
> 
> If this applies to your PR, please make the proper update to your quickstart's config to reference only data sources.

Thank you @brammerl. I have updated this PR by adding datasources files. Could you please review it and guide me if any changes are required.
Thank you 😊

2023-03-04 07:33 UTC, seemantk commented
Keeping this open as the docs for this are almost ready

On Fri, Mar 3, 2023 at 6:01 PM github-actions[bot]
***@***.***> wrote:
>
> Old PRs will be closed after 30 days of inactivity. This PR has been quiet for 14 days and is being marked as stale. Reply here to keep this PR open.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.Message ID: ***@***.***>

2023-03-21 06:59 UTC, seemantk requested changes
Nice work here @pkosanam .  Added some language adjustments to increase clarity

2023-03-21 06:59 UTC, seemantk commented on alert-policies/mexn/FirstContentfulPaint.yml
> +  This alert is triggered when the first contentful paint is taking more than 3 seconds for 5 minutes.
is taking -> takes

2023-03-21 06:59 UTC, seemantk commented on alert-policies/mexn/MongoDBConnectionsCount.yml
> +name: MongoDB Collection Count
Is this supposed to be MongoDB Connection Count?

2023-03-21 06:59 UTC, seemantk commented on alert-policies/mexn/MongoDBConnectionsCount.yml
> +  This alert is triggered when the created MongoDB connections are higher than 2000 for 5 minutes.
Please consider rephrasing to:
This alert is triggered when the there are more than 2000 MongoDB connections created within a 5 minute period.

2023-03-21 06:59 UTC, seemantk commented on alert-policies/mexn/TransactionErrors.yml
> +  This alert is triggered when more than 10 transactions fail for 5 minutes.
more than 10 -> 10 or more

2023-03-21 06:59 UTC, seemantk commented on dashboards/mexn/dashboard.json
> +          "title": "Ajax Request",
Request -> Requests

2023-03-21 07:15 UTC, pkosanam commented
Thank you for your review comments @seemantk
I have updated the code as per your review comments.
Thank you 😃

2023-03-21 17:09 UTC, brammerl commented
Blocks #1598 as it contains a dashboard that #1598 references

2023-03-21 17:10 UTC, brammerl commented on data-sources/mern/config.yml
> +  ## Comprehensive MERN stack monitoring system:
Data source descriptions don't support markdown and are expected to be a short description. Please come up with a short/concise description for this data source

2023-03-21 17:10 UTC, brammerl commented on quickstarts/mern/config.yml
> +
Let's remove this space

2023-03-21 17:11 UTC, brammerl commented on quickstarts/mern/config.yml
> +title: MERN stack
```suggestion
title: MERN Stack
```

2023-03-21 17:13 UTC, brammerl commented on quickstarts/mern/config.yml
> +keywords:
If you want your quickstart to appear under a certain category in add data, please add specific keywords that will map to a specific category. The terms that appear match to the displayName.
[Query](https://api.newrelic.com/graphiql?#query=%7B%0A%20%20actor%20%7B%0A%20%20%20%20nr1Catalog%20%7B%0A%20%20%20%20%20%20categories%20%7B%0A%20%20%20%20%20%20%20%20terms%0A%20%20%20%20%20%20%20%20displayName%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

2023-03-23 16:36 UTC, seemantk approved these changes

2023-03-23 16:36 UTC, merged