Updated Python Dashboard and Alerts
newrelic/newrelic-quickstarts pull request #1628
Opened 2023-02-07 09:06 UTC by sjyothi54

# Summary
Ticket URL:https://issues.newrelic.com/browse/NR-81098
Description: This PR has the updated the Python Dashboards and Alerts.
Screenshots:
![screencapture-newrelic-instant-observability-preview-2023-02-07-14_31_23 (1)](https://user-images.githubusercontent.com/99384747/217200037-7d96bc1c-fdff-46bd-afc3-8316f51e45c4.png)

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Are all documentation links publically accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [ ] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-02-08 12:00 UTC, pkosanam requested changes

2023-02-08 12:00 UTC, pkosanam commented on dashboards/python/python.json
> +			  "text": "![Redmine logo](https://freepngimg.com/thumb/categories/1402.png)\n"
please rename "Redmine logo" to "logo"

2023-02-08 12:45 UTC, pkosanam approved these changes
looks good

2023-02-09 18:56 UTC, brammerl approved these changes

2023-02-09 18:56 UTC, merged