NR-86430 : LAMPy-new quickstart
newrelic/newrelic-quickstarts pull request #1711
Opened 2023-03-21 12:18 UTC by RamanaReddy8801

# Summary

**Ticket URL**: https://issues.newrelic.com/browse/NR-86430

**Description**: This PR has the new quickstart integration named "LAMPy stack"

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

### Screenshot

![screencapture-newrelic-instant-observability-preview-2023-05-12-09_50_21](https://github.com/newrelic/newrelic-quickstarts/assets/106150577/8a57888f-8307-46a0-9691-46af833716a3)

2023-04-24 10:22 UTC, pkosanam requested changes

2023-04-24 10:22 UTC, pkosanam commented on quickstarts/lampy/config.yml
> +  - Multiple high-value alerts  including latest number of questions per second, error transactions percentage , memory usage and more.
Instead of using `and more.`, it would be nice to display the 4th alert.

2023-04-24 10:22 UTC, pkosanam commented on alert-policies/lampy/CpuUtilization.yml
> +  This alert is triggered when the CPU Utilization is above 90% for 5 minutes.
before: `This alert is triggered when the CPU Utilization is above 90% for 5 minutes.`
can be changed to: `This alert is triggered when the CPU utilization exceeds 90% for 5 minutes.`

2023-04-24 10:22 UTC, pkosanam commented on alert-policies/lampy/QuestionsPerSecond.yml
> +  This alert is triggered when the current rate of Questions is greater than 4 for 5 minutes.
before: `This alert is triggered when the current rate of Questions is greater than 4 for 5 minutes.`
can be changed to: `This alert is triggered when the current rate of questions exceeds 4 for 5 minutes.`

2023-04-24 10:22 UTC, pkosanam commented on alert-policies/lampy/HighMemoryUsage.yml
> +  This alert is triggered when the server memory is higher than 90 MB for 5 minutes.
before: `This alert is triggered when the server memory is higher than 90 MB for 5 minutes.`
can be changed to: `This alert is triggered when the server memory exceeds 90 MB for 5 minutes.`

2023-04-24 10:22 UTC, pkosanam commented on alert-policies/lampy/HighMemoryUsage.yml
> +  This alert is triggered when the server memory is higher than 90 MB for 5 minutes.
what is the logic behind 90MB ?
Can we use percent instead ?

2023-04-24 10:22 UTC, pkosanam commented on alert-policies/lampy/QuestionsPerSecond.yml
> +name: Question Per Second
can be changed to: `name: Questions Per Second`

2023-04-24 10:22 UTC, pkosanam commented on alert-policies/lampy/TransactionErrors.yml
> +  This alert is triggered when the transactions fail more than 10% of the time in 5 minutes.
can be changed to: `This alert is triggered when the transactions failure rate exceeds 10% for 5 minutes.`

2023-04-24 10:22 UTC, pkosanam commented on alert-policies/lampy/TransactionErrors.yml
> +  query: "SELECT percentage(count(*), WHERE error is true)  FROM Transaction"
can be changed to: `query: "SELECT percentage(count(*), WHERE error is true) FROM Transaction"

2023-05-17 15:12 UTC, pkosanam approved these changes
looks good

2023-05-17 15:14 UTC, mdumpati approved these changes
Looks good to me

2023-05-17 15:15 UTC, seemantk approved these changes

2023-05-17 15:31 UTC, merged