NR101719: Lighttpd - updated urls for dashboard in About section
newrelic/newrelic-quickstarts pull request #1724
Opened 2023-03-29 11:53 UTC by dikshab0202

Ticket : [NR-101719](https://issues.newrelic.com/browse/NR-101719)
Description: updated urls in About section of  lighttpd dashboard.

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-03-29 12:28 UTC, pkosanam requested changes

2023-03-29 14:32 UTC, dikshab0202 commented on dashboards/lighttpd/lighttpd.json
> +            "text": "**About**\n\nInstrument your application with New Relic - [Add Data](https://one.newrelic.com/catalog-pack-details/nr1-core/home?state=2b90838a-3f1e-07db-001a-6943eef5f6dc).\n\nU
@pkosanam , Existing URL matches the URLs we have given in our previous quickstarts such as PHP, .Net.
Is it new recommendation for "Add Data" url in About section? Please confirm, I'll change accordingly.

2023-03-29 15:42 UTC, pkosanam commented on dashboards/lighttpd/lighttpd.json
> +            "text": "**About**\n\nInstrument your application with New Relic - [Add Data](https://one.newrelic.com/catalog-pack-details/nr1-core/home?state=2b90838a-3f1e-07db-001a-6943eef5f6dc).\n\nU
great.. thank you for mentioning this @dikshab0202 , I have got it clarified from Rahul Basu. Hence let us proceed with your changes.
Thank you 😃

2023-03-29 15:42 UTC, pkosanam approved these changes
looks good

2023-03-30 16:43 UTC, zstix approved these changes

2023-03-30 16:50 UTC, merged