Feat: Add vSphere dashboard
newrelic/newrelic-quickstarts pull request #1744
Opened 2023-04-17 22:02 UTC by Mesverrum

# Summary

Adding a new quickstart for the vSphere OHI.  5 pages, uses dashboard variables

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

2023-04-18 16:48 UTC, MichelLosier requested changes

2023-04-18 16:48 UTC, MichelLosier commented on data-sources/vmware-vsphere/config.yml
> +id: vsphere-integration
A data source for vsphere already exists it looks like: [example query](https://staging-api.newrelic.com/graphiql?#query=%7B%0A%20%20actor%20%7B%0A%20%20%20%20nr1Catalog%20%7B%0A%20%20%20%20%20%20search%28filter%3A%20%7Btypes%3A%20DATA_SOURCE%7D%2C%20query%3A%20%22vmware%22%29%20%7B%0A%20%20%20%20%20%20%20%20results%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20Nr1CatalogDataSource%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20metadata%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20displayName%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20install%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20primary%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Nr1CatalogLinkInstallDirective%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Nr1CatalogNerdletInstallDirective%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20nerdletId%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20nerdletState%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20requiresAccount%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20keywords%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

We wont need to add a new data source here, and instead the quickstart can point to the existing `vmware-vsphere` data source

2023-04-18 16:48 UTC, MichelLosier commented on quickstarts/vmware/vmware-vsphere/config.yml
> +    url: docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration/
Looks like we are missing the `https://` protocol for this url

2023-04-21 20:59 UTC, Mesverrum commented
@MichelLosier This lookd like it'll work better now

2023-04-25 16:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1744) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1744) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: Mesverrum<br/>:x: MichelLosier<br/>:x: caylahamann<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1744) it.</sub>

2023-05-02 17:19 UTC, MichelLosier approved these changes

2023-05-02 18:42 UTC, merged