New Relic Quickstarts: azure-datafactories dashboard
newrelic/newrelic-quickstarts pull request #1757
Opened 2023-05-02 15:08 UTC by dmiyamasu

# Summary

Adding a dashboard to Azure Data Factories

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

2023-05-03 21:42 UTC, seemantk requested changes
@dmiyamasu this dashboard looks very very close to what is already in Azure.  I'm going to schedule some time for you to demo this prior to engineering review of the PR

2023-05-16 16:54 UTC, josephgregoryii approved these changes

2023-05-16 16:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1757) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dmiyamasu<br/>:x: josephgregoryii<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1757) it.</sub>

2023-05-16 16:55 UTC, seemantk approved these changes

2023-05-16 16:55 UTC, merged