Botolytics
newrelic/newrelic-quickstarts pull request #1780
Opened 2023-05-11 13:22 UTC by LindaWeimann

# Summary

Adding Bot'O'lytics Quickstart with 1 Dashboard.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [didn't work, sanitized manually] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard? 

### Alerts

- [no alerts in the quickstart] Did you check that your alerts actually work?

2023-05-11 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1780) it.</sub>

2023-05-11 16:54 UTC, brammerl commented on quickstarts/bot'o'lytics/config.yml
> +id:
please remove this

2023-05-11 16:56 UTC, brammerl commented on quickstarts/bot'o'lytics/config.yml
> +
In order to install the dashboards there needs to be a data source created and assigned to this quickstart. 

https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#data-sources

2023-05-11 16:59 UTC, seemantk requested changes
hi Heiko!  I'm so glad to see this quickstart!!  Just some language changes and we should be good to go on this

2023-05-11 16:59 UTC, seemantk commented on quickstarts/bot'o'lytics/config.yml
> +  On every well used website there are not only real users, but also many many bots. Those can be legitimate bots, like search bots, synthetic checks or other automated calls to your service. But eve
```suggestion
  On every well used website there are not only real users, but also many many bots. Those can be legitimate bots, like search bots, synthetic checks or other automated calls to your service. But even legitimate bots can distort your service's vitals in a way that they no longer represent your real customer's experience.
```

2023-05-11 16:59 UTC, seemantk commented on quickstarts/bot'o'lytics/config.yml
> +  Being able to distinguish real traffic from bot traffic is cruitial in various cases, for example when examining a marketing campain or when analysing your services vitals or service levels.
```suggestion
  Being able to distinguish real traffic from bot traffic is crucial in various cases, for example when examining a marketing campaign or when analyzing your services vitals or service levels.
```

2023-05-11 16:59 UTC, seemantk commented on quickstarts/bot'o'lytics/config.yml
> +  On every well used website there are not only real users, but also many many bots. Those can be legitimate bots, like search bots, synthetic checks or other automated calls to your service. But eve
```suggestion
  On every well used website there are not only real users, but also many many bots. Those can be legitimate bots, like search bots, synthetic checks or other automated calls to your service. But even legitimate bots can distort your service's vitals in a way that they no longer represent your real customer's experience.
```

2023-05-11 16:59 UTC, seemantk commented on quickstarts/bot'o'lytics/config.yml
> +  Being able to distinguish real traffic from bot traffic is cruitial in various cases, for example when examining a marketing campain or when analysing your services vitals or service levels. The Bo
```suggestion
  Being able to distinguish real traffic from bot traffic is crucial in various cases, for example when examining a marketing campaign or when analyaing your services vitals or service levels. The Bot'o'lytic Dashboard enables you to analyze your traffic for bot traffic.
```

2023-05-11 16:59 UTC, seemantk commented on quickstarts/bot'o'lytics/config.yml
> +  ## Bot'O'lytics
```suggestion
  ## Bot'o'lytics
```

2023-05-11 16:59 UTC, seemantk commented on quickstarts/bot'o'lytics/config.yml
> +title: Bot'O'lytics
```suggestion
title: Bot'o'lytics
```

2023-05-16 16:47 UTC, josephgregoryii requested changes
Overall the PR looks good. One thing I would like to change is a couple of naming updates with the files and directories:

- Having a `'` in the directory names may lead to some weird breakage in our code with escaped characters. One idea i may suggest is to replace any `'` with dashes (`-`), or remove them completely.
  - Same with file names, `bot'o'lytics` -> `botolytics` or `bot-o-lytics`
- Can we update the screenshot names to describe the image more?
  - e.g., `Botolytics-bots-vs-real.png`, or something along those lines!

2023-05-16 16:47 UTC, josephgregoryii commented on data-sources/bot'o'lytics/config.yml
> +id: bot'o'lytics
Can we update this to not have any `'`?

2023-05-16 16:47 UTC, josephgregoryii commented on quickstarts/bot'o'lytics/config.yml
> +  - bot'o'lytics
We would want to update this as well!

2023-05-16 16:47 UTC, josephgregoryii commented on quickstarts/bot'o'lytics/config.yml
> +  - bot'o'lytics
here as well

2023-05-23 17:05 UTC, zstix requested changes
Looks like this PR has a few things that still need to be updated:

- Remove the `'` from _all_ filename locations (folder names still include it)
- You have two quickstarts with the same name or ID, remove one
- The quickstart(s) are missing an icon. This is a required item, please add one
- You have two _dashboards_ with the same name or ID, please remove one or update the names

My guess is that you created a new version of the quickstart and dashboard without the `'` character, but didn't remove the old files. Removing those should help with most of the issues (leaving just the icon to resolve).

2023-06-15 16:39 UTC, brammerl commented
Leaving open for now, @seemantk will converse with Heiko about re-creating an updated quickstart

2023-08-24 09:51 UTC, pkosanam commented
Closing this PR, as it got updated on PR- https://github.com/newrelic/newrelic-quickstarts/pull/1932

2023-08-24 09:51 UTC, closed without merging