Project orth star azure fixes
newrelic/newrelic-quickstarts pull request #1789
Opened 2023-05-18 05:08 UTC by glennthomas1

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-05-19 19:02 UTC, seemantk submitted a review, later dismissed

2023-05-19 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1789) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: glennthomas1<br/>:x: seemantk<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1789) it.</sub>

2023-05-23 16:47 UTC, zstix requested changes

2023-05-23 16:47 UTC, zstix commented on dashboards/azure-container-registry/azure-container-registry.json
> +                  11817994
It looks like we have a hard-coded `accountId` here. Unless that is intentional, we should remove that.

2023-05-23 16:47 UTC, zstix commented on dashboards/azure-container-registry/azure-container-registry.json
> +                  11817994
Same comment as above.

2023-05-23 16:47 UTC, zstix commented on dashboards/azure-container-registry/azure-container-registry.json
> +                  11817994
Same comment as above.

2023-05-23 16:47 UTC, zstix commented on dashboards/azure-container-registry/azure-container-registry.json
> +                  11817994
Same comment as above.

2023-05-23 16:47 UTC, zstix commented on dashboards/azure-disk-storage/azure-disk-storage.json
> +                  11817994
As with the other file, we have a hard-coded `accountId` here. Unless intentional, we should remove this.

2023-05-31 06:06 UTC, glennthomas1 commented
Fixed all issues brought up in the comments. Please push these fixes.

2023-06-08 16:43 UTC, seemantk approved these changes

2023-06-12 22:46 UTC, glennthomas1 commented
All merge conflicts resolved. Should be ready to go. Please advise.

2023-06-13 14:35 UTC, glennthomas1 commented
These changes were merged in a different branch by Aarushi Jain on our team. Closing this request in favor of her changes.

2023-06-13 14:35 UTC, closed without merging