Project NorthStar Azure Cohort3
newrelic/newrelic-quickstarts pull request #1790
Opened 2023-05-18 07:18 UTC by glennthomas1

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

Adding 21 new quickstarts/dashboards as part of the Cohort 3 entities of Project NorthStar Azure, from the Product Partnership team.

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [X] Did you check you NRQL syntax? - Does it work?
- [X] Did you include a Data source and Documentation reference?
- [X] Are all documentation links publicly accessible?
- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [X] Did you check your descriptive content for spelling and grammar errors?
- [X] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [X] Does the PR contain a screenshot for each of your dashboards?
- [X] Do your screenshots show data?
- [X] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [X] Did you check that your alerts actually work?

2023-05-18 17:05 UTC, josephgregoryii reviewed
Looks great! couple areas to cleanup, but once those are addressed should be good to go

2023-05-18 17:05 UTC, josephgregoryii commented on quickstarts/azure/azure-hdinsight/config.yml
> +  [New Relic Azure HDInsight](/microsoft-azure-integrations/azure-integrations-list/azure-hdinsight-monitoring-integration/) monitoring quickstart empowers you to track the performance of Azure HDIns
I think we might be missing the host of this link!

2023-05-18 17:05 UTC, josephgregoryii commented on quickstarts/azure/azure-purview/config.yml
> +  [New Relic Microsoft Purview](/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-purview-monitoring-integration/) monitoring quickstart empowers you to track the perfor
Might be missing the host name here as well

2023-05-18 17:15 UTC, josephgregoryii commented
Also to note: There are some dashboards missing images in this PR as well

2023-05-18 17:47 UTC, seemantk commented on quickstarts/azure/azure-app-service-environment/config.yml
> +  [New Relic Azure App Service Environment](//docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-app-service-environment-monitoring-integration/) monitor
```suggestion
  [New Relic Azure App Service Environment](//docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-app-service-environment-monitoring-integration/) monitoring quickstart empowers you to track the performance of Azure App Service Environment via different metrics including account bytes received, bytes sent, cpu percentage, disk queue length, memory percentage. 
```

2023-05-18 18:10 UTC, seemantk requested changes
Main points:

- slugs should match the service name
- quickstarts are not "downloaded"
- verb tenses should be consistent

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-data-explorer/config.yml
> +  Monitoring Azure Data Explorer toolbox gives you an end-to-end solution for data ingestion, query, visualization and management. Download New Relic Azure Data Explorer monitoring quickstart to get
```suggestion
  Monitoring Azure Data Explorer toolbox gives you an end-to-end solution for data ingestion, query, visualization and management. Install the New Relic Azure Data Explorer monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Data Explorer service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-data-lake-analytic/config.yml
> +  Monitoring Azure Data Lake Analytics is critical to track the performance through key metrics. Download New Relic Azure Data Lake Analytics Service monitoring quickstart to get a pre-built dashboar
```suggestion
  Monitoring Azure Data Lake Analytics is critical to tracking the performance through key metrics. Install the New Relic Azure Data Lake Analytics Service monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Data Lake Analytics service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-data-lake-storage/config.yml
> +  Monitoring Azure Data Lake Storage is critical to track the performance through key metrics. Download New Relic Azure Data Lake Storage monitoring quickstart to get a pre-built dashboard tailored t
```suggestion
  Monitoring Azure Data Lake Storage is critical to tracking the performance through key metrics. Install the New Relic Azure Data Lake Storage monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Data Lake Storage service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-device-provisioning-service/config.yml
> +  Monitoring Azure Device Provisioning Service is critical to track the performance through key metrics. Download New Relic Azure Device Provisioning Service monitoring quickstart to get a pre-built
```suggestion
  Monitoring Azure Device Provisioning Service is critical to tracking the performance through key metrics. Install the New Relic Azure Device Provisioning Service monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Device Provisioning Service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-hdinsight/config.yml
> +  Monitoring Azure HDInsight is critical to track the performance through key metrics. Download New Relic Azure HDInsight monitoring quickstart to get a pre-built dashboard tailored to monitor your A
```suggestion
  Monitoring Azure HDInsight is critical to tracking the performance through key metrics. Install the New Relic Azure HDInsight monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure HDInsight service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-integration-service-environment/config.yml
> +  Monitoring Azure Integration Service Environment is critical to track the performance through key metrics. Download New Relic Azure Integration Service Environment monitoring quickstart to  get a p
```suggestion
  Monitoring Azure Integration Service Environment is critical to tracking the performance through key metrics. Install the New Relic Azure Integration Service Environment monitoring quickstart to  get a pre-built dashboard tailored to monitor your Azure Integration Service Environment.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-iot-hub/config.yml
> +  Monitoring Azure IoT Hub is critical to track the performance through key metrics. Download New Relic Azure IoT Hub monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure
```suggestion
  Monitoring Azure IoT Hub is critical to tracking the performance through key metrics. Install the New Relic Azure IoT Hub monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure IoT Hub service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-peering-service/config.yml
> +  Monitoring Azure Peering Service is critical to track the performance through key metrics. Download New Relic Azure Peering Service monitoring quickstart to  get a pre-built dashboard tailored to m
```suggestion
  Monitoring Azure Peering Service is critical to tracking the performance through key metrics. Install the New Relic Azure Peering Service monitoring quickstart to  get a pre-built dashboard tailored to monitor your Azure Peering Service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-peering/config.yml
> +  Monitoring Azure Peering is critical to track the performance through key metrics. Download New Relic Azure Peering monitoring quickstart to  get a pre-built dashboard tailored to monitor your Azur
```suggestion
  Monitoring Azure Peering is critical to tracking the performance through key metrics. Install the New Relic Azure Peering monitoring quickstart to  get a pre-built dashboard tailored to monitor your Azure Peering.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-peering/config.yml
> +  Peering is the interconnection between Microsoft's global network (ASN AS8075) and your network for the purpose of exchanging internet traffic from/to Microsoft online services and Microsoft Azure
```suggestion
  Peering is the interconnection between Microsoft's global network (ASN AS8075) and your network for the purpose of exchanging internet traffic between Microsoft online services and Microsoft Azure Services. Carriers or Service Providers can request to connect at any of Microsoft's edge locations.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-purview/config.yml
> +  Monitoring Microsoft Purview is critical to track the performance through key metrics. Download New Relic Microsoft Purview monitoring quickstart to get a pre-built dashboard tailored to monitor yo
```suggestion
  Monitoring Microsoft Purview is critical to tracking the performance through key metrics. Install the New Relic Microsoft Purview monitoring quickstart to get a pre-built dashboard tailored to monitor your Microsoft Purview service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-stream-analytic/config.yml
> +slug: azure-stream-analytic
Should the slug actually be "azure-stream-analytics" to match the name of the service?

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-stream-analytic/config.yml
> +  Monitoring Azure Stream Analytics is critical to track the performance through key metrics. Download New Relic Azure Stream Analytics monitoring quickstart to get a pre-built dashboard tailored to
```suggestion
  Monitoring Azure Stream Analytics is critical to tracking the performance through key metrics. Install the New Relic Azure Stream Analytics monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Stream Analytics service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-synapse-analytic/config.yml
> +slug: azure-synapse-analytic
Should the slug be `azure-synapse-analytics` to match the name of the service?

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-synapse-analytic/config.yml
> +  Monitoring Azure Synapse Analytics is critical to track the performance through key metrics. Download New Relic Azure Synapse Analytics monitoring quickstart to get a pre-built dashboard tailored t
```suggestion
  Monitoring Azure Synapse Analytics is critical to tracking the performance through key metrics. Install the New Relic Azure Synapse Analytics monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Synapse Analytics service.
```

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-time-series-insight/config.yml
> +slug: azure-time-series-insight
Should the slug be `azure-time-series-insights` to match the name of the service?

2023-05-18 18:10 UTC, seemantk commented on quickstarts/azure/azure-time-series-insight/config.yml
> +  Monitoring Azure Time Series Insights Cloud is a fully visualization service that makes it easy to explore and analyze via key metrics. Download New Relic Azure Time Series Insight monitoring quick
```suggestion
  Monitoring Azure Time Series Insights Cloud is a fully visualization service that makes it easy to explore and analyze via key metrics. Install the New Relic Azure Time Series Insight monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Time Series Insights service.
```

2023-05-19 18:55 UTC, glennthomas1 commented
All issues resolved. Should be ready to go!

2023-05-19 18:59 UTC, seemantk approved these changes
LGTM

2023-05-19 21:53 UTC, josephgregoryii reviewed
Just one last broken docs!

2023-05-19 21:53 UTC, josephgregoryii commented on quickstarts/azure/azure-app-service-environment/config.yml
> +  [New Relic Azure App Service Environment](//docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-app-service-environment-monitoring-integration/) monitor
```suggestion
  [New Relic Azure App Service Environment](https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-app-service-environment-monitoring-integration/) monitoring quickstart empowers you to track the performance of Azure App Service Environment via different metrics including account bytes received, bytes sent, cpu percentage, disk queue length, memory percentage. 
```

2023-05-19 22:36 UTC, glennthomas1 commented
Hopefully that resolves all issues and the merge and push to production can happen. Let me know...

2023-05-19 22:58 UTC, josephgregoryii commented
@glennthomas1 that should be it! once the validations pass i'll send it through

2023-05-19 23:00 UTC, josephgregoryii approved these changes

2023-05-19 23:00 UTC, merged