OpsLevel Quickstart
newrelic/newrelic-quickstarts pull request #1847
Opened 2023-06-16 23:39 UTC by reidan

# Summary

OpsLevel is a Developer Portal tool and we've been building an integration with New Relic. The Quickstart is informational only, we don't have dashboards, data sources or alerts packaged together.

## Pre merge checklist

- [ ] ~Did you check you NRQL syntax? - Does it work?~ (No NRQL)
- [x] Did you include ~a Data source and~ Documentation reference? (No Data Source)
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

No Dashboards

- [ ] ~Does the PR contain a screenshot for each of your dashboards?~
- [ ] ~Do your screenshots show data?~
- [ ] ~Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?~

### Alerts

No Alerts

- [ ] ~Did you check that your alerts actually work?~

2023-06-20 16:42 UTC, seemantk requested changes
Hi @reidan ! Thank you for your contribution.  This is a great start -- once you add a dashboard and/or alerts, we will do a thorough review and put it on the road to merge

2023-06-20 17:13 UTC, reidan commented
Hi @seemantk , thanks for the reply. We've been coordinating with some folks from your team and our current integration involves pulling data from New Relic into OpsLevel and we aren't planning to send any OpsLevel data to New Relic for Dashboards or Alerts at this time.

Is there anything we need to do to highlight that this quickstart is focussed on the documentation to support the integration?

2023-06-20 21:58 UTC, jcountsNR commented
@seemantk , We've been working with them on this one. The integration is with our alerts platform, they are generating workflows to Send New Relic alerts to OpsLevel. So this one won't actually have a traditional dashboard, but we would still like a tile for the functionality that was built.

2023-06-22 16:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1847) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=1847) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: reidan<br/>:white_check_mark: jcountsNR<br/>:x: mickeyryan42<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=1847) it.</sub>

2023-06-22 16:36 UTC, mickeyryan42 approved these changes

2023-06-22 16:40 UTC, merged