NR-89151: Apache ZooKeeper Quickstart
newrelic/newrelic-quickstarts pull request #1858
Opened 2023-06-21 04:28 UTC by RamanaReddy8801

# Summary

**Ticket details**: https://issues.newrelic.com/browse/NR-89151
**Description**: This PR has the new quickstart integration named "Apache ZooKeeper"

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-06-30 10:59 UTC, mdumpati reviewed
@RamanaReddy8801 Check my comments and use only NRI-Flex. No need NRI-ZooKeeper.

2023-07-17 10:29 UTC, pkosanam requested changes

2023-07-17 10:29 UTC, pkosanam commented on alert-policies/apache-zooKeeper/FsyncTime.yml
> +  This alert is triggered when the fsync time exceeds 100 for 5 minutes.
```suggestion
  This alert is triggered when the fsync time exceeds 90 milliseconds for 5 minutes.
```

2023-07-17 10:29 UTC, pkosanam commented on alert-policies/apache-zooKeeper/FsyncTime.yml
> +    threshold: 60
```suggestion
    threshold: 90
```

2023-07-17 10:29 UTC, pkosanam commented on alert-policies/apache-zooKeeper/RejectedConnection.yml
> +name: Rejected Connection
```suggestion
name: Rejected Connections
```

2023-07-17 10:29 UTC, pkosanam commented on alert-policies/apache-zooKeeper/RejectedConnection.yml
> +  This alert is triggered when the rejected connection exceeds 5 for 5 minutes.
```suggestion
  This alert is triggered when the rejected connections exceeds 3 for 5 minutes.
```

2023-07-17 10:29 UTC, pkosanam commented on alert-policies/apache-zooKeeper/WatchNodeChanged.yml
> +name: Watch Node Changed
```suggestion
name: Watch counts on ZooKeeper nodes
```

2023-07-17 10:29 UTC, pkosanam commented on alert-policies/apache-zooKeeper/WatchNodeChanged.yml
> +  This alert is triggered when the watch node changes exceeds 5 for 5 minutes.
```suggestion
  This alert is triggered when the watch counts on znodes exceeds 1 for 5 minutes.
```

2023-07-17 10:29 UTC, pkosanam commented on quickstarts/apache-zooKeeper/config.yml
> +  With Apache ZooKeeper monitoring quickstart by New Relic, you can instantly achieve comprehensive observability across your entire stack, right from the start:
```suggestion
    New Relic Apache ZooKeeper monitoring quickstart provides quality out-of-the-box reporting:
```

2023-07-17 10:29 UTC, pkosanam commented on quickstarts/apache-zooKeeper/config.yml
> +  - Dashboards (ZNode count, watch count, max latency, client connections, etc)
```suggestion
  - Dashboards (znode count, watch count, max latency, client connections, etc)
```

2023-07-17 10:29 UTC, pkosanam commented on quickstarts/apache-zooKeeper/config.yml
> +  - Alerts for zookeeper (Rejected Connection, Changed watch node)
```suggestion
  - Alerts for ZooKeeper (rejected connections, watch counts on ZooKeeper nodes)
```

2023-07-18 09:50 UTC, mdumpati approved these changes
LGTM

2023-07-18 09:51 UTC, merged