NR-115593 MEVN quickstart
newrelic/newrelic-quickstarts pull request #1859
Opened 2023-06-21 05:00 UTC by RamanaReddy8801

# Summary

**Ticket details**: https://issues.newrelic.com/browse/NR-115593
**Description**: This PR has the new quickstart integration named "MEVN"

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-06-30 10:57 UTC, mdumpati reviewed
@RamanaReddy8801 check my comments

2023-06-30 10:57 UTC, mdumpati commented on quickstarts/mevn/config.yml
> +  MEVN stack is a popular Javascript software stack that has become very popular in recent times to build powerful web applications. It comprises four essential components, namely MongoDB, ExpressJS,
```suggestion
  MEVN stack is a popular Javascript software stack that has become very popular in recent times to build powerful web applications. It comprises four essential components, namely MongoDB, ExpressJS, Vue, and NodeJS. These components integrate seamlessly and logically, making it easy to create web applications using this powerful technology stack. Each of these four components has a crucial role to play in the development of web applications.
```

2023-06-30 10:57 UTC, mdumpati commented on quickstarts/mevn/config.yml
> +  - For ExpressJS and NodeJS, there are a variety of metrics available, including web transactions, top ten errors, and memory usage
```suggestion
  - For ExpressJS and NodeJS, there are a variety of metrics available, including web transactions, the top ten errors, and memory usage
```

2023-06-30 10:57 UTC, mdumpati commented on quickstarts/mevn/config.yml
> +  - Vue metrics include viewed urls, page views by city, ajax requests, etc. In addition, you may create your own chart based on the metrics collected
```suggestion
  - Vue metrics include viewed urls, page views by city, AJAX requests, etc. In addition, you may create your own chart based on the metrics collected
```

2023-06-30 10:57 UTC, mdumpati commented on quickstarts/mevn/config.yml
> +  - A number of high-value alerts are available including the average number of connections created, the FCP score and the memory usage
```suggestion
  - A number of high-value alerts are available including the average number of connections created, the FCP score and memory usage
```

2023-07-17 10:48 UTC, pkosanam requested changes

2023-07-17 10:48 UTC, pkosanam commented on quickstarts/mevn/config.yml
> +
```suggestion
  - MongoDB metrics such as active connections, database details, and usage time
  - For ExpressJS and NodeJS, there are a variety of metrics available, including web transactions, the top ten errors, and memory usage
  - Vue metrics include viewed urls, page views by city, AJAX requests, etc. In addition, you may create your own chart based on the metrics collected
```

2023-07-17 10:48 UTC, pkosanam commented on quickstarts/mevn/config.yml
> +
can remove lines 16 to 19

2023-07-17 10:48 UTC, pkosanam commented on quickstarts/mevn/config.yml
> +  - Informative dashboards (the top 10 transactions, connections, database indexes, and more)
can remove line 24

2023-07-17 10:48 UTC, pkosanam commented on quickstarts/mevn/config.yml
> +  - A number of high-value alerts are available including the average number of connections created, the FCP score and memory usage
line 23 will be mentioned at the last after all the bullet points

2023-07-18 09:17 UTC, seemantk approved these changes
lgtm

2023-07-18 09:51 UTC, mdumpati approved these changes
LGTM

2023-07-18 10:17 UTC, pkosanam approved these changes
LGTM

2023-07-18 13:04 UTC, merged