WordPress Full Stack quickstart - creation
newrelic/newrelic-quickstarts pull request #1860
Opened 2023-06-22 09:25 UTC by pkosanam

Ticket ID: https://issues.newrelic.com/browse/NR-128789

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-06-22 10:03 UTC, pkosanam commented
need to update the docs links, hence converting this PR to draft

2023-07-17 11:02 UTC, pkosanam commented on quickstarts/wordpress-fullstack/config.yml
> +  - full stack
add
```
  - word press
```

2023-07-17 15:28 UTC, pkosanam commented on quickstarts/wordpress-fullstack/config.yml
> +  - Browser metrics like page view comparison, TTFB and more
done

2023-07-17 15:28 UTC, pkosanam commented on quickstarts/wordpress-fullstack/config.yml
> +  - full stack
done

2023-07-18 09:21 UTC, seemantk requested changes
minor language changes

2023-07-18 15:44 UTC, pkosanam commented on quickstarts/wordpress-fullstack/config.yml
> +  - Transactions and its error messages
done

2023-07-26 09:40 UTC, seemantk commented on quickstarts/wordpress-fullstack/config.yml
> +  - Easily identify the plugin(s) that consumes the most time and resources
@pkosanam the requested changes are not being seen, can you please verify?

2023-07-26 12:41 UTC, seemantk approved these changes
lgtm, thanks @pkosanam

2023-07-26 14:08 UTC, merged