[WIP] feat: Add dockerstats quickstart
newrelic/newrelic-quickstarts pull request #1881
Opened 2023-07-17 07:18 UTC by gsanchezgavier

# Summary

Adds a quickstart for the Dockerstats receiver of Opentelemetry collector

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-07-17 07:43 UTC, gsanchezgavier commented
@mangulonr

2023-07-17 14:59 UTC, sigilioso commented on dashboards/docker-otel/docker-otel.json
> +        }
May we remove these defaults?

2023-07-18 06:05 UTC, gsanchezgavier commented on dashboards/docker-otel/docker-otel.json
> +        }
for sure, good catch.

2023-07-18 06:09 UTC, gsanchezgavier commented on dashboards/docker-otel/docker-otel.json
> +        }
done

2023-07-19 08:34 UTC, mangulonr approved these changes

2023-08-07 08:28 UTC, mangulonr commented
Hi @seemantk

2023-08-09 11:06 UTC, pkosanam requested changes
Thank you for these changes and request you to kindly add few alert conditions also.
Doc Ref: https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#alerts

2023-08-10 09:11 UTC, gsanchezgavier commented on quickstarts/docker-otel/config.yml
> +      virtualization to deliver software in packages called containers.
done [2dfd5f4](https://github.com/newrelic/newrelic-quickstarts/pull/1881/commits/2dfd5f433461d104595d6079ddc31e2f8b45c11d)

2023-08-10 09:11 UTC, gsanchezgavier commented on quickstarts/docker-otel/config.yml
> +  A New Relic container Entity will represent each of the containers making it easy to explore, alert, and compare metrics related to them.
done [2dfd5f4](https://github.com/newrelic/newrelic-quickstarts/pull/1881/commits/2dfd5f433461d104595d6079ddc31e2f8b45c11d)

2023-08-10 09:11 UTC, gsanchezgavier commented on quickstarts/docker-otel/config.yml
> +  New Relic's Docker for Open Telemetry quickstart empowers you to get a 360° visibility for your apps, server infrastructure, and Dockerized containers—all in one place. Since your team is likely ch
done [2dfd5f4](https://github.com/newrelic/newrelic-quickstarts/pull/1881/commits/2dfd5f433461d104595d6079ddc31e2f8b45c11d)

2023-08-10 09:11 UTC, gsanchezgavier commented on quickstarts/docker-otel/config.yml
> +  Monitoring Docker is critical to get instant performance metrics for containerized applications across your entire environment. Install New Relic Docker for Open Telemetry quickstart to proactively
done [2dfd5f4](https://github.com/newrelic/newrelic-quickstarts/pull/1881/commits/2dfd5f433461d104595d6079ddc31e2f8b45c11d)

2023-08-10 09:11 UTC, gsanchezgavier commented on install/docker-otel/install.yml
> +id: docker-otel
done [2dfd5f4](https://github.com/newrelic/newrelic-quickstarts/pull/1881/commits/2dfd5f433461d104595d6079ddc31e2f8b45c11d)

2023-08-10 09:11 UTC, gsanchezgavier commented on quickstarts/docker-otel/config.yml
> +  - docker-otel
done [2dfd5f4](https://github.com/newrelic/newrelic-quickstarts/pull/1881/commits/2dfd5f433461d104595d6079ddc31e2f8b45c11d)

2023-08-10 09:44 UTC, seemantk approved these changes
LGTM, thank you for making the changes so quickly

2023-08-10 09:53 UTC, pkosanam approved these changes
Looks good to me

2023-08-10 09:53 UTC, pkosanam commented on alert-policies/docker-otel/MemoryUtilization.yml
> +  This alert is triggered when the Memory Utilization is above 90%.
```suggestion
  This alert is triggered when the Memory utilization exceeds 90%.
```

2023-08-10 09:53 UTC, pkosanam commented on alert-policies/docker-otel/MemoryUtilization.yml
> +
```suggestion
  - priority: WARNING
    # Operator used to compare against the threshold.
    operator: ABOVE
    # Value that triggers a violation
    threshold: 85
    # Time in seconds; 120 - 3600
    thresholdDuration: 300
    # How many data points must be in violation for the duration
    thresholdOccurrences: ALL
```

2023-08-10 09:55 UTC, merged