Botolytics Quickstart
newrelic/newrelic-quickstarts pull request #1932
Opened 2023-08-16 07:27 UTC by sjyothi54

## Description:
Raising this PR inorder to address all the comments mentioned in the PR: https://github.com/newrelic/newrelic-quickstarts/pull/1780
Ticket URL:https://issues.newrelic.com/browse/NR-150069
## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-08-16 09:46 UTC, mdumpati requested changes
@sjyothi54 Please change Bot'o'lytics to Botolytics everywhere.

2023-08-16 09:46 UTC, mdumpati commented on install/botolytics/install.yml
> +title: Bot'o'lytics
```suggestion
title: Botolytics
```

2023-08-16 09:46 UTC, mdumpati commented on quickstarts/botolytics/config.yml
> +title: Bot'o'lytics
```suggestion
title: Botolytics
```

2023-08-16 09:46 UTC, mdumpati commented on data-sources/botolytics/config.yml
> +displayName: Bot'o'lytics
```suggestion
displayName: Botolytics
```

2023-08-16 09:48 UTC, mdumpati commented on quickstarts/botolytics/config.yml
> +  - boto'o'lytics
No need this line

2023-08-17 09:46 UTC, mdumpati requested changes
@sjyothi54 check my comments

2023-08-17 09:46 UTC, mdumpati commented on quickstarts/botolytics/config.yml
> +id:
```suggestion
id:
```
Please mention id here or remove

2023-08-17 09:47 UTC, mdumpati requested changes

2023-08-17 09:47 UTC, mdumpati commented on quickstarts/botolytics/config.yml
> +
@sjyothi54 add apm and addData keyword here.

2023-08-17 16:47 UTC, brammerl commented on install/botolytics/install.yml
> +id: botolytics
Please delete this file as instlalPlans are deprecated

2023-08-17 16:47 UTC, brammerl commented on quickstarts/botolytics/config.yml
> +  - NR1_addData
```suggestion
```

2023-08-17 16:48 UTC, brammerl commented on quickstarts/botolytics/config.yml
> +  - NR1_addData
We don't want to add quickstarts to add data unless explicitly approved by a PM and Jumpstart team.

2023-08-17 16:48 UTC, brammerl commented on quickstarts/botolytics/config.yml
> +  - botolytics
```suggestion

```

2023-08-17 16:51 UTC, brammerl commented on quickstarts/botolytics/config.yml
> +  - botolytics
```suggestion
  - guided-install
```

2023-08-17 16:52 UTC, brammerl commented on data-sources/botolytics/config.yml
> +
Since we're deciding to go with guided install data source we can also delete this.

2023-08-23 10:06 UTC, mdumpati approved these changes
LGTM

2023-08-23 10:07 UTC, seemantk approved these changes

2023-08-23 10:07 UTC, merged