LangChain Quickstart
newrelic/newrelic-quickstarts pull request #2005
Opened 2023-09-04 10:09 UTC by sjyothi54

**Ticket URL:** https://issues.newrelic.com/browse/NR-156585
**Description:** Created LangChain quickstart

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-09-05 07:19 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  With this quickstart, you will:
```suggestion
  With this quickstart, you will be able:
```

2023-09-05 07:21 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  ### To track performance:
```suggestion
  ### Track performance:  
```

2023-09-05 07:22 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  ### To improve the model:
```suggestion
  ### Improve the model: 
```

2023-09-05 07:26 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  By monitoring the performance of LangChain AI, you will identify areas where the model will be improved. For example, you will track things like the accuracy of the model's predictions and the dive
```suggestion
  Monitoring the performance of LangChain AI allows for the identification of areas where the model can be improved. For example, tracking the accuracy of the model's predictions and the diversity of the model's responses.
```

2023-09-05 07:29 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  Our LangChain quickstart provides you metrics such as uptime, accuracy, relevance, and speed. These metrics can help you ensure that LangChain AI is performing at its best.
Our LangChain quickstart provides metrics, including uptime, accuracy, relevance, and speed. These metrics serve as valuable tools to empower you in maximizing the performance of LangChain AI.

2023-09-05 07:34 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  New Relic LangChain monitoring quickstart provides quality out-of-the-box reporting:
```suggestion
  New Relic LangChain monitoring quickstart offers a range of out-of-the-box reports, including:
```

2023-09-05 16:52 UTC, d3caf commented on quickstarts/mlops/langchain/config.yml
> +  Monitoring the performance of LangChain AI will help you identify areas where you will improve. For example, you will track things like latency, throughput, and error rates.
Maybe rephrase these sentences?

2023-09-05 16:53 UTC, d3caf commented on quickstarts/mlops/langchain/config.yml
> +  - Alerts (errors,requests per model and response time)
Reword this a bit as well. The `including` doesn't really flow with the bullet points

2023-09-05 16:54 UTC, d3caf approved these changes

2023-09-06 06:44 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  Monitoring the performance of LangChain AI will help you identify areas where you will improve. For example, you will track things like latency, throughput, and error rates.
```suggestion
  By tracking key metrics like latency, throughput, and error rates, you can gain insights into LangChain AI's performance and identify areas of improvement.
```

2023-09-06 06:50 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  New Relic LangChain monitoring quickstart offers a range of out-of-the-box reports, including:
```suggestion
 New Relic LangChain monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your LangChain. These reports include:
```

2023-09-06 06:52 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  - Gain code-related insights about your LangChain's health and status
```suggestion
  - Get code-related insights to identify potential problems with your code and improve its performance.
```

2023-09-06 06:55 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  - Monitor your LangChain latency and tokens
Track the latency details and number of tokens

2023-09-06 07:11 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  - Entity (average tokens, cost, total requests, api response time and many more)
```suggestion
  - Entity details such as the average number of tokens used, the cost per entity, and the total number of requests made
```

2023-09-06 07:16 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  - Alerts (errors,requests per model and response time)
```suggestion
  - Alerts for errors, requests per model, and response time.
```

2023-09-06 07:18 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  Use the New Relic LangChain quickstart to improve the performance of your LangChain.
```suggestion
  Improve your LangChain Performance with New Relic LangChain Quickstart.
```

2023-09-07 07:48 UTC, rahulbasu-nr commented on alert-policies/langchain/error.yml
> +  This alert is triggered if the number of errors is greater than 0 within 5 minutes.
```suggestion
  This alert is triggered if the number of errors is greater than 0 for 5 minutes.
```

2023-09-07 07:50 UTC, rahulbasu-nr commented on alert-policies/langchain/requestsPerModel.yml
> +  This alert is triggered if requests per model exceeds 1000 in 5 minutes.
```suggestion
  This alert is triggered if requests per model exceeds 1000 for 5 minutes.
```

2023-09-07 07:52 UTC, rahulbasu-nr commented on alert-policies/langchain/responseTime.yml
> +  This alert is triggered if response time exceeds 5 seconds in 5 minutes.
```suggestion
  This alert is triggered if response time exceeds 5 seconds for 5 minutes.
```

2023-09-07 11:22 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  LangChain is a framework for developing applications powered by language models. New Relic LangChain quickstart performance monitoring offers immediate and pre-configured observability.
```suggestion
 Monitoring LangChain will help you to ensure its performance, identify and prevent outages, detect security threats, gather performance metrics, and identify potential opportunities for collaboration or integration.
```

2023-09-07 11:34 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  ## Why monitor LangChain?
```suggestion
  ## Why monitor your LangChain powered application?
```

2023-09-07 11:45 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  LangChain is a framework for developing applications powered by language models. New Relic LangChain quickstart performance monitoring offers immediate and pre-configured observability.
```suggestion
  LangChain is a framework for developing applications powered by language models. By monitoring your LangChain app, we are providing you visibility on the chains, tools as well as inputs and outputs.
```

2023-09-07 11:46 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  ### Ensure uptime:
```suggestion
   
```

2023-09-07 11:46 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  LangChain AI is a complex system, and it is important to make sure that it is always up and running. By monitoring the system, you will quickly identify and fix any issues that may cause downtime.
```suggestion
```

2023-09-07 11:47 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  LangChain AI is a complex system, and it is important to make sure that it is always up and running. By monitoring the system, you will quickly identify and fix any issues that may cause downtime.
```suggestion
  
```

2023-09-07 11:51 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  By tracking key metrics like latency, throughput, and error rates, you can gain insights into LangChain AI's performance and identify areas of improvement.
```suggestion
  ### Track your app:  
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your LangChain app's performance and identify areas of improvement.
```

2023-09-07 11:56 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  Monitoring the performance of LangChain AI allows for the identification of areas where the model can be improved. For example, tracking the accuracy of the model's predictions and the diversity of
```suggestion
  ### Track the LLM's performance: 
  Monitor the input/output, latency and errors of your LLM provider. Track performance changes depending upon the versions and providers of your LLM. 
  
  
  Monitor the usage to understand the cost, rate limits and general performance.
  
  
  
```

2023-09-07 12:07 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  Our LangChain quickstart provides metrics, including uptime, accuracy, relevance, and speed. These metrics serve as valuable tools to empower you in maximizing the performance of LangChain AI.
```suggestion
  ## Comprehensive monitoring quickstart for your LangChain app
  Our LangChain quickstart provides metrics, including error rate, input/output, latency, queries, retrieved document content, integrate different LLM providers and vector stores.
```

2023-09-07 12:08 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  New Relic LangChain monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your LangChain. These reports include:
```suggestion
  New Relic LangChain monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your LangChain app. These reports include:
```

2023-09-07 12:09 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +  - Alerts for errors,requests per model and response time
```suggestion
  - LLM calls and chains
  - Tools
  - Vector searches
  - Alerts for errors, requests per model and response time
```

2023-09-07 12:11 UTC, rahulbasu-nr commented on quickstarts/mlops/langchain/config.yml
> +     Implement monitoring and instrumentation for your LangChain, and ensure that your LangChain data is integrated into New Relic for effective performance analysis and insights.
```suggestion
     Implement monitoring and instrumentation for your LangChain app, to ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
```

2023-09-07 12:16 UTC, rahulbasu-nr commented on alert-policies/langchain/error.yml
> +  This alert is triggered if the number of errors is greater than 0 within 5 minutes.
```suggestion
  This alert is triggered if the number of errors exceeds 2 within 5 minutes.
```

2023-09-07 12:16 UTC, rahulbasu-nr commented on alert-policies/langchain/error.yml
> +    threshold: 0
```suggestion
    threshold: 2
```

2023-09-07 12:26 UTC, rahulbasu-nr requested changes
.

2023-09-07 14:06 UTC, pkosanam requested changes

2023-09-07 14:06 UTC, pkosanam commented on data-sources/langchain/config.yml
> +      url: https://github.com/newrelic/nr-openai-observability
```suggestion
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: langchain-vectordb
      requiresAccount: false
```

2023-09-07 14:06 UTC, pkosanam commented on data-sources/langchain/config.yml
> +    link:
```suggestion
```

2023-09-07 19:47 UTC, mdumpati approved these changes
LGTM

2023-09-07 19:48 UTC, pkosanam submitted a review, later dismissed
LGTM

2023-09-07 19:49 UTC, seemantk submitted a review, later dismissed
lgtm

2023-09-07 19:54 UTC, pkosanam commented on dashboards/langchain/langchain.json
> +  "name": "LangChain",
```suggestion
  "name": "LangChain Application",
```

2023-09-07 19:56 UTC, mdumpati approved these changes
LGTM

2023-09-07 19:57 UTC, seemantk approved these changes
lgtm

2023-09-07 19:57 UTC, merged