Datazoom Updates
newrelic/newrelic-quickstarts pull request #2048
Opened 2023-09-08 19:58 UTC by cjmccarthy

# Summary

Updating the logo and dashboard image as requested by DZ team

2023-09-08 19:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2048) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2048) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2048) it.</sub>

2023-09-19 16:51 UTC, sarahkitten requested changes
Hey! Images should be in 16:9 format so that they fit properly on the site, can we update the new dashboard image to meet this requirement?

2023-10-17 16:32 UTC, aswanson-nr commented
Hey @cjmccarthy, this is looking good, we'd just like to get a widescreen (16:9) screenshot. In it's current portrait layout, it will not display well on the website.

2023-10-17 17:37 UTC, cjmccarthy commented
Sorry for the delay on the update, folks. I chunked the screenshot out into several of the appropriate aspect ratio

2023-10-19 16:40 UTC, sarahkitten approved these changes

2023-10-19 16:47 UTC, merged