AwaDB new quickstart
newrelic/newrelic-quickstarts pull request #2078
Opened 2023-09-27 10:08 UTC by RamanaReddy8801

# Summary

**Ticket**: https://issues.newrelic.com/browse/NR-164845
**Description**: Created AwaDB Quickstart.

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-10-10 09:58 UTC, rahulbasu-nr commented on quickstarts/awadb/config.yml
> +  Our AwaDB quickstart provides metrics including Identify popular queries, sources, and content.
```suggestion
  Our AwaDB quickstart provides insights like identifying popular queries, sources, and content.
```

2023-10-10 10:06 UTC, rahulbasu-nr requested changes
Please make these changes

2023-10-12 08:14 UTC, rahulbasu-nr approved these changes
Looks good to me.

2023-10-12 08:41 UTC, mdumpati approved these changes
LGTM

2023-10-12 09:06 UTC, merged