Hologres Matching Engine Quickstart
newrelic/newrelic-quickstarts pull request #2079
Opened 2023-09-27 11:01 UTC by sjyothi54

**Ticket:** https://issues.newrelic.com/browse/NR-164851
**Description:** Created Hologres Matching Engine Quickstart

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-10-10 09:47 UTC, rahulbasu-nr commented on quickstarts/hologres-matching-engine/config.yml
> +  ## Why should you monitor your usage of Hologres Matching Engine?
```suggestion
  ## Why should you monitor Hologres Matching Engine?
```

2023-10-10 09:51 UTC, rahulbasu-nr commented on quickstarts/hologres-matching-engine/config.yml
> +  - real-time graph processing
```suggestion
  - real-time graph processing
  - real time graph processing
```

2023-10-10 10:08 UTC, rahulbasu-nr requested changes
Please make the changes.

2023-10-11 06:10 UTC, sjyothi54 commented
> Please make the changes.

@rahulbasu-nr I have updated the changes, kindly review it.

2023-10-12 08:15 UTC, rahulbasu-nr approved these changes
Looks good to me.

2023-10-12 08:40 UTC, mdumpati approved these changes
LGTM

2023-10-12 08:42 UTC, merged