feat(golden-signals-dashboard): Added a golden signals dashboard
newrelic/newrelic-quickstarts pull request #2083
Opened 2023-09-27 16:03 UTC by zahra-siddiqa

Added a dashobard to monitor all golden signals 

# Summary

Adding a dashboard to monitor all golden signals across APM, Infrastructure, Synthetics, Browser and Mobile. 

## Pre merge checklist

- [X] Did you check you NRQL syntax? - Does it work?
- [X] Did you include a Data source and Documentation reference?
- [X] Are all documentation links publicly accessible?
- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [X] Did you check your descriptive content for spelling and grammar errors?
- [X] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [X] Does the PR contain a screenshot for each of your dashboards?
- [X] Do your screenshots show data?
- [X] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts - There are no alerts

- [ ] Did you check that your alerts actually work?

2023-10-12 08:26 UTC, rahulbasu-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +  Monitoring the golden signals allows you to quickly see an overview of the health of your application. This dashboard lets you monitor golden signals across APM, Infrastructure, Synthetics, Browser
```suggestion
  Monitoring the golden signals allows you to quickly see an overview of the health of your application. This dashboard lets you monitor golden signals across APM, Infrastructure, Synthetics, Browser and Mobile with template variables to dynamically filter widgets.
```

2023-10-12 08:27 UTC, rahulbasu-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +  - name: Instal APM agent
```suggestion
  - name: Install APM agent
```

2023-10-12 08:27 UTC, rahulbasu-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +  - name: Instal Infrastructure agent
```suggestion
  - name: Install Infrastructure agent
```

2023-10-12 08:31 UTC, rahulbasu-nr requested changes
Please make these changes.

2023-10-12 08:31 UTC, rahulbasu-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +  - name: Set up Synthteics Monitors
```suggestion
  - name: Set up Synthetics Monitors
```

2023-10-12 08:31 UTC, rahulbasu-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +  - name: Instal Browser agent
```suggestion
  - name: Install Browser agent
```

2023-10-12 08:31 UTC, rahulbasu-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +  - name: Instal Mobile agent
```suggestion
  - name: Install Mobile agent
```

2023-10-12 08:31 UTC, rahulbasu-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +  - errors
```suggestion
  - errors
  - error rates
```

2023-10-17 11:51 UTC, rahulbasu-nr requested changes
Can you please make this change? Thanks.

2023-10-18 09:16 UTC, rahulbasu-nr submitted a review, later dismissed
Looks good to me.

2023-10-19 06:35 UTC, mdumpati approved these changes
LGTM

2023-10-19 16:51 UTC, aswanson-nr requested changes
Hey @zahra-siddiqa, this looks great! Just saw one problem with the quickstart slug. 
Also, could you sign the CLA? We need that to be signed before we can merge.

2023-10-19 16:51 UTC, aswanson-nr commented on quickstarts/golden-signals-dashboard/config.yml
> +slug: golden-signals-dashboard-for-New-Relic
The slug needs to be lower case:
```suggestion
slug: golden-signals-dashboard-for-new-relic
```

2023-11-09 18:02 UTC, rahulbasu-nr commented
Hello Zahra! I'm having difficulty locating a data source for this PR. @aswanson-nr, could you kindly advise if it's ready to proceed?

2023-11-10 16:47 UTC, zahra-siddiqa commented
> Hello @zahra-siddiqa ! I'm having difficulty locating a data source for this PR. @aswanson-nr, could you kindly advise if it's ready to proceed?

Hi @rahulbasu-nr, the datasource for this dashboard is the data coming from New Relic APM, Infrastructure, Synthetics, Browser and Mobile. Do you need me to add this in the quickstart config file?

2023-11-15 15:14 UTC, rahulbasu-nr commented
Yes Zahra! datasourceIds needs to be added to the config.yml file. Kindly follow this file as a [reference](https://github.com/newrelic/newrelic-quickstarts/blob/main/quickstarts/mean/config.yml).

2023-11-16 17:47 UTC, sarahkitten approved these changes

2023-11-16 17:47 UTC, merged