Vectara Quickstart
newrelic/newrelic-quickstarts pull request #2091
Opened 2023-09-29 15:55 UTC by sjyothi54

**Ticket URL:** https://issues.newrelic.com/browse/NR-164852
**Description:** Created Vectara Quickstart

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-10-17 12:19 UTC, rahulbasu-nr requested changes
Please use the SVG file format from the offical website - https://vectara.com/wp-content/uploads/2022/08/vectara-color-logo.svg

2023-10-18 04:57 UTC, sjyothi54 commented
> Please use the SVG file format from the offical website - https://vectara.com/wp-content/uploads/2022/08/vectara-color-logo.svg

@rahulbasu-nr Updated the logo, Kindly review this PR.

2023-10-18 09:48 UTC, rahulbasu-nr requested changes
Please make these changes.

2023-10-18 09:48 UTC, rahulbasu-nr commented on quickstarts/vectara/config.yml
> +  ### Track the query performance of your Vector DB
```suggestion
  ### Track the query performance of Vectara
```

2023-10-18 09:48 UTC, rahulbasu-nr commented on quickstarts/vectara/config.yml
> +  ### Track your app:
```suggestion
  ### Track the health of Vectara
```

2023-10-18 09:48 UTC, rahulbasu-nr commented on quickstarts/vectara/config.yml
> +  Monitor your vector searches on Vectara to get visibility on what you send to Vectara, responses retrieved from Vectara, latency, usage and errors.
```suggestion
  Monitor your vector searches with Vectara to gain insights into the data you're sending to it, the responses you're receiving, the latency, usage, and any potential errors.
```

2023-10-18 09:48 UTC, rahulbasu-nr commented on quickstarts/vectara/config.yml
> +  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your app's performance and identify areas of improvement.
```suggestion
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into Vectara's performance and identify areas of improvement.
```

2023-10-18 09:48 UTC, rahulbasu-nr commented on quickstarts/vectara/config.yml
> +  New Relic Vectara monitoring quickstart provides a variety of pre-built dashboards, which will help you gain insights into the health and performance of your Vectara app. These reports include:
```suggestion
  New Relic Vectara monitoring quickstart provides a variety of pre-built dashboards, which will help you gain insights into the health and performance of Vectara. These reports include:
```

2023-10-18 09:48 UTC, rahulbasu-nr commented on quickstarts/vectara/config.yml
> +      Implement monitoring and instrumentation for your Vector store, and ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
```suggestion
      Implement monitoring and instrumentation for your Vectara, and ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
```

2023-10-18 11:50 UTC, sjyothi54 commented
> Please make these changes.

Updated the changes

2023-10-23 09:21 UTC, rahulbasu-nr approved these changes
Looks good to me.

2023-10-26 05:27 UTC, merged