NVIDIA DCGM - New AI Quickstart
newrelic/newrelic-quickstarts pull request #2133
Opened 2023-10-31 10:22 UTC by RamanaReddy8801

# Summary

**Ticket**: https://new-relic.atlassian.net/browse/NR-174994
**Description**: Created NVIDIA DCGM quickstart.

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2023-11-01 09:30 UTC, rahulbasu-nr requested changes
Please make these changes.

2023-11-01 09:30 UTC, rahulbasu-nr commented on alert-policies/nvidia-dcgm/HighTemperature.yml
> +  This alert is triggered when the Nvidia GPU Temperature is above 90%.
```suggestion
  This alert is triggered when the NVIDIA GPU Temperature is above 90%.
```

2023-11-01 09:30 UTC, rahulbasu-nr commented on dashboards/nvidia-dcgm/nvidia-dcgm.json
> +            "text": "![NVIDIA DCGM](https://assets.nvidiagrid.net/ngc/logos/DCGM.png)"
Use the NVIDIA logo from - https://github.com/newrelic/newrelic-quickstarts/assets/104448291/461421da-3f8b-4d71-bac7-2e20d58b4180 Check this in dark theme too.

2023-11-01 09:30 UTC, rahulbasu-nr commented on dashboards/nvidia-dcgm/nvidia-dcgm.json
> +          "title": "Total nvlink bandwidth",
```suggestion
          "title": "Total NVLink bandwidth",
```

2023-11-01 09:30 UTC, rahulbasu-nr commented on dashboards/nvidia-dcgm/nvidia-dcgm.json
> +            "text": "**About**\n\nInstrument your application with New Relic - [Add Data](https://one.newrelic.com).\n\nInstrument NVIDIA DCGM with New Relic using the [documentation](https://docs.ne
```suggestion
            "text": "**About**\n\nInstrument your application with New Relic - [Add Data](https://one.newrelic.com).\n\nInstrument NVIDIA DCGM with New Relic using the [documentation](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-dcgm-integration/).\n\n[Please rate this dashboard](https://docs.google.com/forms/d/e/1FAIpQLSclR38J8WbbB2J1tHnllKUkzWZkJhf4SrJGyavpMd4t82NjnQ/viewform?usp=pp_url&entry.1615922415=nvidia-dcgm) here and let us know how we can improve it for you."
```

2023-11-01 09:30 UTC, rahulbasu-nr commented on data-sources/nvidia-dcgm/logo.png
Use the logo image from https://github-production-user-asset-6210df.s3.amazonaws.com/104448291/279630087-461421da-3f8b-4d71-bac7-2e20d58b4180.png

2023-11-01 09:30 UTC, rahulbasu-nr commented on quickstarts/nvidia-dcgm/config.yml
> +  - Dashboards (power usage, gpu utilisation, clocks, etc)
```suggestion
  - Dashboards (power usage, GPU utilisation, clocks, etc)
```

2023-11-01 09:30 UTC, rahulbasu-nr commented on quickstarts/nvidia-dcgm/config.yml
> +  - Alerts for ZooKeeper (gpu temperature, xid error)
```suggestion
  - Alerts for NVIDIA DCGM (GPU temperature, Xid error)
```

2023-11-01 09:30 UTC, rahulbasu-nr commented on quickstarts/nvidia-dcgm/config.yml
> +  - NVIDIA DCGM
```suggestion
  - NVIDIA DCGM
  - AI Acceleration
  - Machine Learning Acceleration
  - GPU Management
  - AI Management
  - Machine Learning Management
  - Deep Learning Performance
  - AI Performance
  - GPU Optimization
  - AI Optimization

```

2023-11-01 09:30 UTC, rahulbasu-nr commented on quickstarts/nvidia-dcgm/logo.png
Use the logo image from https://github-production-user-asset-6210df.s3.amazonaws.com/104448291/279630087-461421da-3f8b-4d71-bac7-2e20d58b4180.png

2023-11-07 17:55 UTC, mickeyryan42 commented on data-sources/nvidia-dcgm/config.yml
> +keywords:
For this to show up in the Add data page, you'll need to add a keyword of `NR1_addData`

2023-11-07 17:59 UTC, mickeyryan42 requested changes
LGTM, We'll just want to add the keyword i commented separately

2023-11-08 09:17 UTC, rahulbasu-nr submitted a review, later dismissed
Looks good to me.

2023-11-09 04:39 UTC, pkosanam approved these changes
LGTM

2023-11-09 17:33 UTC, mickeyryan42 approved these changes

2023-11-09 17:33 UTC, rahulbasu-nr approved these changes
Looks good to me.

2023-11-09 17:34 UTC, merged