NR-155179 Added Gcp Dahsboards
newrelic/newrelic-quickstarts pull request #2156
Opened 2023-12-04 06:03 UTC by rajut-xrg

# Summary
Added New dashboards for GCP

1. GCP Cloud Run
2. GCP Cloud SQL
3. GCP Dataproc
4. GCP Application Load Balancer
5. GCP Redis
6. GCP VPC Access Connector
7. GCP AppEngine
8. GCP BigQuery
9. GCP BigTable
10. GCP Cloud PUB/SUB
11.  GCP Cloud storage
12. GCP Cloud Function
13. GCP Data flow
14. GCP Data store
15. GCP Firebase database
16. GCP firebase hosting

There are still more to addign the dashbaord, which will be created a separate PR

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ NA] Are all documentation links publicly accessible?
- [ NA] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

2023-12-08 09:07 UTC, rajut-xrg commented
Hi Team, could anybody start looking into this PR. Its been waiting from long time

2023-12-11 16:25 UTC, tmarchand-nr commented
Hello -- do you have an estimate about when this PR can be reviewed?

2023-12-12 22:02 UTC, aswanson-nr reviewed
These dashboards look good to me! Just so you're aware, these will not be published as is, since they are not connected to a quickstart. That being said, we can move forward and merge them into the repository and they will be published as they are added to quickstarts. I also noticed one small change needed for the `gcp-cloud-functions` dashboard.

2023-12-12 22:02 UTC, aswanson-nr commented on dashboards/gcp-colud-functions/gcp-cloud-functions.json
> +  "permissions": "PUBLIC_READ_WRITE",
Just need to remove this line! We add a generic permission during installation.
```suggestion
```

2024-01-09 18:01 UTC, sarahkitten requested changes

2024-01-09 18:01 UTC, sarahkitten commented on quickstarts/gcp/gcp-composer/config.yml
> +id:
Let's remove this line (the ID gets automatically generated)

2024-01-09 18:01 UTC, sarahkitten commented on quickstarts/gcp/gcp-memcache/config.yml
> +id:
Let's remove this line

2024-01-24 16:27 UTC, tmarchand-nr commented
Keep open!

2024-02-15 17:40 UTC, sarahkitten commented
@tmarchand-nr can you address the requested changes here

2024-02-15 19:47 UTC, sarahkitten commented
closing as this is already addressed by https://github.com/newrelic/newrelic-quickstarts/pull/2262

2024-02-15 19:47 UTC, closed without merging