NR-155179 Azure qs dashboards
newrelic/newrelic-quickstarts pull request #2166
Opened 2023-12-14 16:54 UTC by rajut-xrg

# Summary
Added dashbaords related to azure, below are the list
1. Azure Logic Apps
2. Azure VPN Gateways
3. Azure SQL
4. Azure SQL managed instance
5. Azure Front Door
6. Azure Load Balancer
7. Azure Virtual machine scale sets
8. Azure SQL Managed Instances
9. Azure Redis Cache

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

2024-01-03 23:39 UTC, aswanson-nr commented
not stale

2024-01-11 18:03 UTC, sarahkitten commented on quickstarts/azure/azure-app-gateway/config.yml
> + Azure Application Gateway is a web traffic (OSI layer 7) load balancer that enables you to manage traffic to your web applications.
```suggestion
  Azure Application Gateway is a web traffic (OSI layer 7) load balancer that enables you to manage traffic to your web applications. 
```

2024-01-17 09:58 UTC, pkudikyala commented on quickstarts/azure/azure-app-gateway/config.yml
> +  - azure-infrastructure-monitoring
```suggestion
installPlans:
  - azure-infrastructure-monitoring
```

2024-01-17 10:14 UTC, pkudikyala requested changes
Please update requested changes.

2024-01-17 10:14 UTC, pkudikyala commented on quickstarts/azure/azure-vpn-gateways/config.yml
> +  - azure-vpn-gateway
```suggestion
  - azure-vpn-gateways
```

2024-02-08 17:37 UTC, d3caf commented
Closing because this was done in #2264

2024-02-08 17:37 UTC, closed without merging