fixed dashboard
newrelic/newrelic-quickstarts pull request #2169
Opened 2023-12-18 16:51 UTC by sami2ahmed

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-01-23 17:50 UTC, brammerl commented on dashboards/confluent-cloud/confluent-cloud.json
> +                "accountId": 3974333,
These should be 0

2024-01-23 17:51 UTC, brammerl commented on dashboards/confluent-cloud/confluent-cloud.json
> +        "accountIds": [3974333],
This should be any empty array

2024-01-23 17:51 UTC, brammerl requested changes
Left some comments on how to improve this.

2024-02-15 17:42 UTC, closed without merging

2024-02-15 17:42 UTC, sarahkitten commented
@sami2ahmed these ids are intentional as this is a template to be used on any account - we're going to close this ticket now, feel free to reopen if you disagree