chore: update akamai quickstart
newrelic/newrelic-quickstarts pull request #2270
Opened 2024-02-01 21:59 UTC by jcountsNR

small changes include renaming to correct name for datastream and slight updates to description for akamai.

2024-02-05 10:05 UTC, RamanaReddy8801 requested changes
Please look into the suggested changes.

2024-02-05 10:05 UTC, RamanaReddy8801 commented on quickstarts/datastream2-akamai/config.yml
> +    - Cache hit retio
```suggestion
    - Cache hit ratio
```

2024-02-15 17:46 UTC, sarahkitten commented
@RamanaReddy8801 can you approve this? committed your suggestion

2024-02-16 04:54 UTC, RamanaReddy8801 approved these changes
LGTM!

2024-02-20 17:47 UTC, merged