New Boomi tile
newrelic/newrelic-quickstarts pull request #2280
Opened 2024-02-08 22:47 UTC by jcountsNR

# Summary
 
Boomi has an example configuration using OTeL to send traces to NR. Traces are automatically dropped into an entity generated by the OTeL collector. This tile just calls that out. Since the data is in traces only, there is no accompanying dashboard.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-02-12 09:52 UTC, mdumpati approved these changes
LGTM

2024-02-20 17:38 UTC, d3caf requested changes
Thanks for creating this! At the moment, we aren't accepting any new data sources created by Relics with install experiences that aren't created in the framework. Feel free to reach out to @rahulbasu-nr if you have any questions!

2024-03-07 17:35 UTC, brammerl approved these changes

2024-03-07 18:06 UTC, d3caf approved these changes

2024-03-07 18:21 UTC, merged