feat(onepane): Added a quickstart for onepane
newrelic/newrelic-quickstarts pull request #2310
Opened 2024-03-06 04:50 UTC by sajosam

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

2024-03-06 04:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2310) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2310) before we can accept your contribution.<br/><hr/>**sajosam** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2310) it.</sub>

2024-03-11 18:03 UTC, jcountsNR commented
@sajosam Thanks for the submission! I think there are a few points with this one.

1. There should still be a quickstart defined in the quickstarts directory that points to this data-source.
2. The longer description of 'what is onepane' could be moved there, since the datasource description would be fit into a very small tile. The datasource description should be very minimal, something like `connect OnePane change tracking to New Relic`.

The second point is also why the submission is failing. Once you move the longer description over to a quickstart, then it wouldn't have this issue.

2024-03-12 15:12 UTC, mdumpati reviewed
@sajosam enter correct url?

2024-03-12 15:12 UTC, mdumpati commented on quickstarts/onepane/config.yml
> +    url: dhttps://www.onepane.ai/docs/en/articles/8999270-adding-onepane-change-tracking-to-your-new-relic-deployment
```suggestion
    url: https://www.onepane.ai/docs/en/articles/8999270-adding-onepane-change-tracking-to-your-new-relic-deployment
```

2024-03-12 15:14 UTC, RamanaReddy8801 requested changes

2024-03-12 15:14 UTC, RamanaReddy8801 commented on quickstarts/onepane/config.yml
> +id: 00000-0000-0000-0000000
```suggestion

```

2024-03-14 06:47 UTC, sajosam commented
Thanks for the feedback @RamanaReddy8801! 
The issue has been resolved.

2024-03-14 15:17 UTC, RamanaReddy8801 approved these changes
LGTM!

2024-03-19 15:07 UTC, merged