Envoy Quickstart
newrelic/newrelic-quickstarts pull request #2317
Opened 2024-03-13 07:18 UTC by sjyothi54

**Ticket:** https://new-relic.atlassian.net/browse/NR-231691
**Description:** Created new Envoy quickstart

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-03-19 15:37 UTC, pkudikyala requested changes
Hi @sjyothi54,
Could you please make the review changes.

2024-03-19 15:37 UTC, pkudikyala commented on alert-policies/envoy/ClusterBindErrors.yml
> +  - priority: WARNING
Remove the warning condition.

2024-03-19 15:37 UTC, pkudikyala commented on alert-policies/envoy/ClusterUpdateFailed.yml
> +  - priority: WARNING
Remove the warning condition.

2024-03-19 15:37 UTC, pkudikyala commented on alert-policies/envoy/DrainingListener.yml
> +  - priority: WARNING
Remove the warning condition.

2024-03-19 15:37 UTC, pkudikyala commented on quickstarts/envoy/config.yml
> +  - NR1_addData
Please add the NR1_sys keyword.

2024-03-26 04:37 UTC, sjyothi54 commented
> Hi @sjyothi54, Could you please make the review changes.

@pkudikyala Made the requested changes, Kindly review it

2024-03-26 04:52 UTC, pkudikyala submitted a review, later dismissed
LGTM!

2024-03-26 15:43 UTC, mdumpati approved these changes
LGTM

2024-03-26 15:44 UTC, pkudikyala approved these changes
LGTM!

2024-03-26 15:44 UTC, merged