Druid Quickstart
newrelic/newrelic-quickstarts pull request #2318
Opened 2024-03-13 09:02 UTC by RamanaReddy8801

# Summary
Ticket: https://new-relic.atlassian.net/browse/NR-234861
Description: Created new Apache Druid quickstart

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [X] Did you check you NRQL syntax? - Does it work?
- [X] Did you include a Data source and Documentation reference?
- [X] Are all documentation links publicly accessible?
- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [X] Did you check your descriptive content for spelling and grammar errors?
- [X] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [X] Does the PR contain a screenshot for each of your dashboards?
- [X] Do your screenshots show data?
- [X] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [X] Did you check that your alerts actually work?

2024-03-19 15:30 UTC, pkudikyala requested changes
Hi @RamanaReddy8801 ,
Could you please make the review changes.

2024-03-19 15:30 UTC, pkudikyala commented on alert-policies/apache-druid/jvmMemoryUsage.yml
> +    threshold: 90
```suggestion
    threshold: 95
```

2024-03-19 15:30 UTC, pkudikyala commented on alert-policies/apache-druid/jvmMemoryUsage.yml
> +    threshold: 80
```suggestion
    threshold: 90
```

2024-04-01 09:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2318) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2318) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2318) it.</sub>

2024-04-02 15:49 UTC, sjyothi54 approved these changes
LGTM

2024-04-02 15:50 UTC, pkudikyala approved these changes
LGTM!

2024-04-02 15:50 UTC, merged