feat : Added Quickstarts for vert.x eventbus and extensions - New Relic Labs
newrelic/newrelic-quickstarts pull request #2322
Opened 2024-03-19 11:28 UTC by gsidhwani-nr

…ic Labs

# Summary

Added Quickstarts for vert.x eventbus and extensions - New Relic Labs
Pre-Existing Java Dashboards, Alerts  are included in Quickstart.

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [X ] Did you check you NRQL syntax? - Does it work?
- [X] Did you include a Data source and Documentation reference?
- [X] Are all documentation links publicly accessible?
- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [X ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-03-19 15:22 UTC, pkudikyala requested changes
Hi @gsidhwani-nr ,
Could you make the review changes.

2024-03-19 15:22 UTC, pkudikyala commented on quickstarts/java/vertx-eventbus/config.yml
> +id:
```suggestion

```

2024-03-19 15:22 UTC, pkudikyala commented on quickstarts/java/vertx-extensions/config.yml
> +id:
```suggestion

```

2024-03-20 03:58 UTC, gsidhwani-nr commented
The requested changes have been committed.

2024-03-21 14:59 UTC, pkudikyala approved these changes
LGTM!

2024-03-21 15:05 UTC, merged