Added a quickstart for APM,BROWSER,MOBILE,INFRA
newrelic/newrelic-quickstarts pull request #2325
Opened 2024-03-22 08:50 UTC by DarrenDoyle

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ Y] Did you check you NRQL syntax? - Does it work?
- [ Y] Did you include a Data source and Documentation reference?
- [ Y] Are all documentation links publicly accessible?
- [ Y] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [Y] Did you check your descriptive content for spelling and grammar errors?
- [ Y] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ Y] Does the PR contain a screenshot for each of your dashboards?
- [ Y] Do your screenshots show data?
- [ Y] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-04-01 09:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2325) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2325) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2325) it.</sub>

2024-04-11 10:14 UTC, DarrenDoyle commented
@pkudikyala FYI Let me know if I have any issues

2024-04-11 16:37 UTC, aswanson-nr commented on quickstarts/mobile-signals /config.yml
Here as well.

2024-04-12 07:13 UTC, DarrenDoyle commented on data-sources/apm-signals /config.yml
Fix

2024-04-12 07:14 UTC, DarrenDoyle commented on data-sources/browser-signals /config.yml
fix

2024-04-12 07:14 UTC, DarrenDoyle commented on data-sources/mobile-signals /config.yml
fix

2024-04-12 07:19 UTC, DarrenDoyle commented on quickstarts/browser-signals /config.yml
fix

2024-04-12 07:19 UTC, DarrenDoyle commented on quickstarts/mobile-signals /config.yml
fix

2024-04-12 07:26 UTC, DarrenDoyle commented
thanks @aswanson-nr & @pkudikyala

2024-04-12 15:32 UTC, aswanson-nr requested changes
Looks like there is a little indentation problem

2024-04-12 15:32 UTC, aswanson-nr commented on data-sources/browser-signals/config.yml
> +  icon: logo.svg
The formatting is a little messed up here
```suggestion
icon: logo.svg
```

2024-04-12 15:32 UTC, aswanson-nr approved these changes
Looks good to go!

2024-04-12 15:37 UTC, aswanson-nr approved these changes
LGTM. Also targeted the `release` branch instead of `main`. @DarrenDoyle just FYI, due to some changes in the publishing process, we now merge into `release` instead of targeting the `main` branch.

2024-04-12 15:37 UTC, merged