NVML Quickstart
newrelic/newrelic-quickstarts pull request #2379
Opened 2024-04-23 09:55 UTC by RamanaReddy8801

**Ticket**: https://new-relic.atlassian.net/browse/NR-258991
**Description**: Created new NVML quickstart
# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-04-23 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2379) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2379) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: RamanaReddy8801<br/>:x: mickeyryan42<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2379) it.</sub>

2024-05-14 15:52 UTC, sjyothi54 requested changes
@RamanaReddy8801 Change the nvml logo to nvidia official logo and work on requested changes

2024-05-14 15:52 UTC, sjyothi54 commented on quickstarts/nvml/config.yml
> +  - Alerts for NVML (GPU temperature, Power usage)
```suggestion
  - Alerts for NVML (GPU temperature, power usage)
```

2024-05-14 15:52 UTC, sjyothi54 commented on quickstarts/nvml/config.yml
> +  - NVIDIA
```suggestion
  - NVIDIA
  - NVIDIA Management library
```

2024-05-15 05:24 UTC, sjyothi54 approved these changes
Looks good

2024-05-16 08:41 UTC, pkudikyala approved these changes
LGTM

2024-05-16 16:49 UTC, merged