Joseph/awsstoragelens
newrelic/newrelic-quickstarts pull request #2387
Opened 2024-04-29 16:20 UTC by jcountsNR

# Summary

Dashboard for storagelens. This data comes in via cloudwatch metrics, so the integration is already in place.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-05-02 15:17 UTC, pkudikyala requested changes
Could you remove the SINCE condition in each query, if it is not required.

2024-05-02 15:17 UTC, pkudikyala commented on dashboards/amazon-s3-storagelens/amazon-s3-storagelens.json
> +              "text": "![New Relic logo](https://lh6.googleusercontent.com/eY3HD-U5lVs38NUsZIgraXMVSuMDfopVCUihlytZ9e6-tF_na-3ENIBte7l05mfPrpp7MXUY_vnmyeS5QlDN1xqm00HrHEoxPkHIAi1BERTdjZZKAraFeIzJ1I6t
```suggestion
              "text": "![AWS S3 Storage Lens logo](https://lh6.googleusercontent.com/eY3HD-U5lVs38NUsZIgraXMVSuMDfopVCUihlytZ9e6-tF_na-3ENIBte7l05mfPrpp7MXUY_vnmyeS5QlDN1xqm00HrHEoxPkHIAi1BERTdjZZKAraFeIzJ1I6ts_hYnLzXes1a)\n# AWS S3 Storage Lens Dashboard"
```

2024-05-06 15:47 UTC, jcountsNR commented
> Could you remove the SINCE condition in each query, if it is not required.

The 'SINCE' in this case is actually crucial. These metrics come in only once per day, so the query needs to be exactly 1 day unless they are timeseries, then they need to be a few days grouped by 1 day.

2024-05-07 14:59 UTC, pkudikyala commented
> > Could you remove the SINCE condition in each query, if it is not required.
> 
> The 'SINCE' in this case is actually crucial. These metrics come in only once per day, so the query needs to be exactly 1 day unless they are timeseries, then they need to be a few days grouped by 1 day.

Okay, thanks for the clarification.

2024-05-07 15:00 UTC, pkudikyala approved these changes
LGTM!

2024-05-07 15:01 UTC, RamanaReddy8801 approved these changes
LGTM

2024-05-07 15:10 UTC, merged