feat: Apache mesos quickstart
newrelic/newrelic-quickstarts pull request #2415
Opened 2024-05-21 09:24 UTC by sjyothi54

**Ticket:** https://new-relic.atlassian.net/browse/NR-264786
**Description:** Created new Apache mesos quickstart

## Pre merge checklist

- [X] Did you check you NRQL syntax? - Does it work?
- [X] Did you include a Data source and Documentation reference?
- [X] Are all documentation links publicly accessible?
- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [X] Did you check your descriptive content for spelling and grammar errors?
- [X] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [X] Does the PR contain a screenshot for each of your dashboards?
- [X] Do your screenshots show data?
- [X] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [X] Did you check that your alerts actually work?

2024-05-21 15:18 UTC, RamanaReddy8801 requested changes

2024-05-21 15:18 UTC, RamanaReddy8801 commented on quickstarts/apache-mesos/config.yml
> +  The Apache Mesos quickstart involves monitoring by tracking Master uptime, cluster status, and the statuses of tasks, frameworks, and agents. This comprehensive approach ensures a clear view of sys
```suggestion
The Apache Mesos quickstart involves monitoring by tracking master uptime, cluster status, and the statuses of tasks, frameworks, and agents. This comprehensive approach ensures a clear view of system health and performance, facilitating proactive management and rapid issue resolution.
```

2024-05-21 15:18 UTC, RamanaReddy8801 commented on quickstarts/apache-mesos/config.yml
> +  - Dashboards (Master uptime, cluster status, tasks status, framework status, agent status and logs)
```suggestion
  - Dashboards (master uptime, cluster status, tasks status, framework status, agent status and logs)
```

2024-05-22 07:02 UTC, RamanaReddy8801 approved these changes
LGTM!

2024-05-23 15:40 UTC, pkudikyala approved these changes
LGTM!

2024-05-24 05:47 UTC, merged