feat: Linkerd quickstart
newrelic/newrelic-quickstarts pull request #2427
Opened 2024-06-04 12:44 UTC by shivanikash

# Summary

Ticket: https://new-relic.atlassian.net/browse/NR-273970
Description: Created new linkerd quickstart

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you include a Data source and Documentation reference?
- [ ] Are all documentation links publicly accessible?
- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [ ] Did you check your descriptive content for spelling and grammar errors?
- [ ] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [ ] Does the PR contain a screenshot for each of your dashboards?
- [ ] Do your screenshots show data?
- [ ] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?

2024-06-04 12:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2427) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2427) it.</sub>

2024-06-04 15:59 UTC, sjyothi54 requested changes
@shivanikash Kindly work on the requested changes

2024-06-04 15:59 UTC, sjyothi54 commented on alert-policies/linkerd/ExcessTCPConnections.yml
> +  This alert is triggered when tcp open connections exceeds 150 for 5 minutes.
```suggestion
  This alert is triggered when TCP open connections exceeds 150 for 5 minutes. 
```

2024-06-04 15:59 UTC, sjyothi54 commented on alert-policies/linkerd/HighResponseLatency.yml
> +  This alert is triggered when response latency exceeds 200 for 5 minutes.
```suggestion
  This alert is triggered when response latency exceeds 200 ms for 5 minutes.
```

2024-06-04 16:08 UTC, shivanikash commented on alert-policies/linkerd/ExcessTCPConnections.yml
> +  This alert is triggered when tcp open connections exceeds 150 for 5 minutes.
done

2024-06-06 15:03 UTC, RamanaReddy8801 approved these changes
LGTM!

2024-06-06 15:04 UTC, sjyothi54 approved these changes
Looks good

2024-06-06 15:04 UTC, merged