fix: Cleaning up AI Monitoring quickstarts
newrelic/newrelic-quickstarts pull request #2482
Opened 2024-07-15 17:58 UTC by RyanKadri

# Summary

This PR cleans up a couple AI Monitoring quickstarts:
- Removes or fixes old/misleading alert conditions for LangChain and OpenAI
- Point the Azure OpenAI quickstart to the correct installation wizard
- Point the LangChain quickstart to the correct installation wizard and removes an outdated dashboard in favor of curated AIM landing pages.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [x] Did you check that your alerts actually work?

2024-07-15 17:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2482) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2482) it.</sub>

2024-07-16 14:25 UTC, RamanaReddy8801 requested changes
@RyanKadri, please make requested changes and change the alert file name `responseTime.yml` to `duration.yml`

2024-07-16 14:25 UTC, RamanaReddy8801 commented on quickstarts/mlops/langchain/config.yml
> +dashboards: []
```suggestion

```

2024-07-16 14:25 UTC, RamanaReddy8801 commented on alert-policies/langchain/responseTime.yml
>    This alert is triggered if response time exceeds 5 seconds in 5 minutes.
```suggestion
  This alert is triggered if duration exceeds 5 seconds in 5 minutes.
```

2024-07-22 15:52 UTC, RyanKadri commented
@RamanaReddy8801 I made those changes. How do things look now? Thanks!

2024-07-24 06:15 UTC, sjyothi54 approved these changes
Looks good

2024-07-24 06:16 UTC, RamanaReddy8801 approved these changes
LGTM

2024-07-24 06:51 UTC, merged