Point Ollama to the updated AI Monitoring installer
newrelic/newrelic-quickstarts pull request #2483
Opened 2024-07-15 18:12 UTC by RyanKadri

# Summary

This points the Ollama quickstart to the new AI Monitoring installation approach (directly through the APM agent). The default dashboard does not really make sense for an app that uses Ollama so I'm removing the link to that. The curated AI Monitoring pages (or the new entity's page) is probably where we should send the user but it doesn't seem like we can easily hook that up via the quickstart config

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [x] Did you check that your alerts actually work?

2024-07-15 18:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2483) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=2483) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2483) it.</sub>

2024-07-16 14:18 UTC, sjyothi54 requested changes
@RyanKadri Please work on this change

2024-07-16 14:18 UTC, sjyothi54 commented on quickstarts/ollama/config.yml
> +dashboards: []
```suggestion

```

2024-07-22 15:47 UTC, RyanKadri commented on quickstarts/ollama/config.yml
> +dashboards: []
@sjyothi54 done :)

2024-07-22 16:40 UTC, sjyothi54 approved these changes
Looks good

2024-07-24 06:14 UTC, RamanaReddy8801 approved these changes
LGTM

2024-07-24 06:17 UTC, merged