Rename quickstart (after initial feedback)
newrelic/newrelic-quickstarts pull request #2597
Opened 2024-10-24 18:41 UTC by JimHagan

# Summary

After some early feedback from the field I renamed this quickstart to `nrql-query-performance` to make it more positive and a little easier to find.

2024-10-25 06:32 UTC, sjyothi54 requested changes
@JimHagan Could you please modify the title as well?

2024-10-25 06:32 UTC, sjyothi54 commented on quickstarts/nrql-query-performance/config.yml
>  title: Slow Query Analytics
```suggestion
title: NRQL Query Performance
```

2024-10-28 20:25 UTC, JimHagan commented
> @JimHagan Could you please modify the title as well?

Done.  Thanks for catching that.

2024-10-29 04:23 UTC, sjyothi54 approved these changes
LGTM

2024-10-29 09:16 UTC, RamanaReddy8801 approved these changes
LGTM

2024-10-29 09:17 UTC, merged