chore: contribute-update
newrelic/newrelic-quickstarts pull request #345
Opened 2021-09-23 18:23 UTC by jpvajda

Updated contributor guide and adds a PR checklist the PR Template.

2021-09-23 19:08 UTC, aswanson-nr commented
The repository has been renamed to `newrelic/newrelic-quickstarts`. Github will handle routing your remotes to this new url, but we recommend that you update your remote as soon as possible.
**NOTE**: As part of this change, we have moved all the quickstarts from the `/packs` directory to the `/quickstarts` directory. To bring your pull request up to date, please pull in the latest commits from the `main` branch.

Use the following command to set your new remote:
```bash
git remote set-url origin https://github.com/newrelic/newrelic-quickstarts.git
```

Or with an SSH origin
```bash
git remote set-url origin git@github.com:newrelic/newrelic-quickstarts.git
```

2021-09-23 22:43 UTC, nr-kkenney commented on .github/pull_request_template.md
> +-[ ] Did you checks that your alerts actually work?
typo here.

2021-09-23 23:02 UTC, aswanson-nr requested changes
Just two small typos! Content looks great

2021-09-23 23:02 UTC, aswanson-nr commented on .github/pull_request_template.md
> +new quickstart please review the Pre merge checklist section to validate this PR is ready for review.
```suggestion
new quickstart please review the pre merge checklist section to validate this PR is ready for review.
```

2021-09-23 23:02 UTC, aswanson-nr commented on .github/pull_request_template.md
> +-[ ] Did you checks that your alerts actually work?
```suggestion
-[ ] Did you check that your alerts actually work?
```

2021-09-23 23:25 UTC, jpvajda commented on .github/pull_request_template.md
> +-[ ] Did you checks that your alerts actually work?
That was in my smeagol voice.

2021-09-24 18:53 UTC, nr-kkenney commented on quickstarts/dotnet/dotnet/config.yml
> +  Learn more about.NET Framework, the importance of monitoring .NET, the ideal features of a .NET monitor, and the unique value of New Relic's .NET quickstart.
```suggestion
  Learn more about .NET Framework, the importance of monitoring .NET, the ideal features of a .NET monitor, and the unique value of New Relic's .NET quickstart.
```

2021-09-24 20:12 UTC, nr-kkenney submitted a review, later dismissed

2021-09-24 20:27 UTC, aswanson-nr submitted a review, later dismissed

2021-09-24 21:12 UTC, aswanson-nr approved these changes

2021-09-24 22:18 UTC, merged