Marked Istio adapter as deprecated
newrelic/newrelic-quickstarts pull request #379
Opened 2021-09-27 22:38 UTC by bpschmitt

# Summary

The Istio adapter linked in Quickstarts is no longer supported and the repo has essentially been abandoned.  Newer versions of Istio do not utilize the Istio Mixer and that component has been deprecated as of Istio v1.7.  Istio is currently at v1.11.3.

## Pre merge checklist

N/A

-[X] Did you check your descriptive content for voice, tone, spelling and grammar errors?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

N/A

2021-09-27 22:45 UTC, jpvajda requested changes

2021-09-27 22:45 UTC, jpvajda commented on quickstarts/istio/config.yml
> +name: istio (Deprecated)
```suggestion
name: istio
```

2021-09-27 22:45 UTC, jpvajda commented on quickstarts/istio/config.yml
> +name: istio (Deprecated)
Just removing this as I think it will look a bit odd in the UI, and the deprecation notice is in the summary.

2021-09-27 22:45 UTC, jpvajda commented on quickstarts/istio/config.yml
>    platforms together in a single point.
```suggestion
  platforms together in a single point.  NOTE: This adapter requires the Istio Mixer component which was deprecated after Istio v1.7
```

2021-09-27 22:45 UTC, jpvajda commented on quickstarts/istio/config.yml
>    platforms together in a single point.
adding to the description as well.

2021-09-27 23:14 UTC, bpschmitt commented on quickstarts/istio/config.yml
>    platforms together in a single point.
Looks good.

2021-09-28 00:29 UTC, jpvajda approved these changes

2021-09-28 00:30 UTC, merged

2021-09-28 00:30 UTC, jpvajda commented
-[ ]
- [ ]