Add mlops/dagshub
newrelic/newrelic-quickstarts pull request #395
Opened 2021-09-29 06:37 UTC by simonlsk

# Summary

Added DagsHub pack under `mlops`.
The `config.yml` file still needs to be authored.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

2021-09-29 06:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=395) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=395) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=395) it.</sub>

2021-09-29 12:50 UTC, polfliet requested changes
Hey @simonlsk! Thanks for your contribution!

2021-09-29 12:50 UTC, polfliet commented on packs/mlops/dagshub/config.yml
> +  - dagshub-mlops
This installPlan will have to be created, similar to the example for Algorithmia here https://github.com/newrelic/newrelic-quickstarts/blob/main/install/mlops/algorithmia/install.yml.
Can you add that installPlan to the PR?

2021-09-29 12:50 UTC, polfliet commented on packs/mlops/dagshub/dashboards/dagshub.json
> +                "query": "SELECT latest(loss) FROM Metric TIMESERIES SINCE 1800 seconds ago"
(disclaimer: I don't know anything about DagsHub)
Will this `loss` event be available for every user that sets up DagsHub?
The goal of the dashboard is that it should work for every user who tries this out.

Are there other charts that could be added to make this a compelling dashboard?
Or does this really depend on the customer's use case? Maybe in that case, would it make sense to use a markdown widget on the dashboard and provide some more info?

2021-11-06 15:02 UTC, jpvajda commented
I am closing this PR due to the age and no response from the contributor. If you'd like to resubmit this, we can re-open when you have time to resolve the feedback @simonlsk  Thank you!

2021-11-16 16:03 UTC, simonlsk commented
@jpvajda I took care of the required changes. Can you reopen?

2021-11-16 18:57 UTC, jpvajda commented
@simonlsk Thanks I re-opened the PR!

2021-11-16 19:00 UTC, jpvajda commented
@simonlsk this is failing the schema compliance check could you take a [look at the erro](https://github.com/newrelic/newrelic-quickstarts/runs/4229216714?check_suite_focus=true)r and try to resolve?

2021-11-18 12:16 UTC, rudouglas requested changes
Just a couple of small changes

2021-11-18 12:16 UTC, rudouglas commented on quickstarts/mlops/dagshub/config.yml
> +id:
```suggestion
```

The id will be autogenerated so you can remove this line

2021-11-18 12:16 UTC, rudouglas commented on quickstarts/mlops/dagshub/config.yml
> +  - machine-learning
```suggestion
```

2021-11-18 12:41 UTC, rudouglas approved these changes

2021-11-18 12:41 UTC, merged