Dashboard for Log Analysis
newrelic/newrelic-quickstarts pull request #475
Opened 2021-10-12 13:44 UTC by thcanate

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.
![log-analysis](https://user-images.githubusercontent.com/19784240/136967620-a92a611c-012d-448a-9dbb-f47bd814e3ee.png)

2021-10-12 13:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-quickstarts?pullRequest=475) before we can accept your contribution.<br/><hr/>**tanate** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=475) it.</sub>

2021-10-13 21:42 UTC, roadlittledawn requested changes

2021-10-13 23:29 UTC, thcanate commented on importer-config.sh
> +apiKey=
Removed the file from gitignore

2021-10-13 23:29 UTC, thcanate commented on quickstarts/log-analysis/dashboards/log-analysis.json
> +  "permissions": "PRIVATE",
Removed the permission

2021-10-13 23:30 UTC, thcanate commented on quickstarts/log-analysis/config.yml
> +    url: https://docs.newrelic.com/docs/logs/
changed the URL link.

2021-10-14 17:47 UTC, roadlittledawn approved these changes
Thanks for making those changes! LGTM. :shipit:

2021-10-14 17:48 UTC, merged