feat(sendgrid): Add installPlans for SendGrid Event Webhook and S3 log ingestion
newrelic/newrelic-quickstarts pull request #523
Opened 2021-10-27 23:46 UTC by ktst79

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2021-11-03 02:00 UTC, ktst79 commented
Can I know the status of this PR?

2021-11-06 15:19 UTC, jpvajda requested changes
Thanks for the contribution, just a few suggestions here.

2021-11-06 15:19 UTC, jpvajda commented on install/aws/aws-log-ingestion-s3/install.yml
> +  You can send your Amazon S3 buckets to New Relic using our AWS Lambda function, NewRelic-log-ingestion-s3
```suggestion
  You can send your Amazon S3 buckets to New Relic using our AWS Lambda function, NewRelic-log-ingestion-s3.
```

2021-11-06 15:19 UTC, jpvajda commented on install/aws/aws-log-ingestion-s3/install.yml
> +      https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-logs-s3/
```suggestion
      https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-logs-s3/
      
```

2021-11-06 15:19 UTC, jpvajda commented on install/third-party/sendgrid/install.yml
> +    SendGrid provides a cloud-based service that assists businesses with email delivery. In order to integrate SendGrid Events with New Relic, you will need to send SendGrid events by using the SendG
```suggestion
    SendGrid provides a cloud-based service that assists businesses with email delivery. In order to integrate SendGrid Events with New Relic, you will need to send SendGrid events by using the SendGrid Event Webhook. If you are already sending events to AWS S3 using the SendGrid Event Webhook, these events can be transferred to New Relic by using NewRelic-log-ingestion-s3.
```

2021-11-06 15:19 UTC, jpvajda commented on install/third-party/sendgrid/install.yml
> +    url: https://docs.sendgrid.com/for-developers/tracking-events/getting-started-event-webhook
```suggestion
    url: https://docs.sendgrid.com/for-developers/tracking-events/getting-started-event-webhook
    
```

2021-11-08 21:28 UTC, jpvajda approved these changes

2021-11-08 21:28 UTC, merged

2021-11-09 10:34 UTC, ktst79 commented
Thanks! @jpvajda

2021-11-09 13:58 UTC, jpvajda commented
@ktst79 Thank you for the contribution! 🚀