Added Amazon QLDB pack
newrelic/newrelic-quickstarts pull request #531
Opened 2021-10-29 08:54 UTC by EmilHammarstrand

# Summary

Added dashboard images.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

2021-11-06 15:33 UTC, jpvajda commented
This is failing a PR check @EmilHammarstrand could you resolve? - Thank you! 

```
 Error: quickstarts/aws/aws-qldb/dashboards/qldb.json
	 '#/not' must NOT be valid
	 '#/additionalProperties' must NOT have additional properties
```

2021-11-06 15:35 UTC, jpvajda requested changes

2021-11-06 15:35 UTC, jpvajda commented on quickstarts/aws/aws-qldb/config.yml
> +  Check out the [documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-qldb-monitoring-integration) to learn more about New Relic monitoring for AWS
@bradleycamacho any suggestions on this description?

2021-11-06 15:35 UTC, jpvajda commented on quickstarts/aws/aws-qldb/config.yml
> +  Check out the [documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-qldb-monitoring-integration) to learn more about New Relic monitoring for AWS
I'd probably recommend including some details of how we describe this on the docs page

New Relic offers an integration for reporting your Amazon Quantum Ledger Database (QLDB) data to New Relic. This document explains how to activate this integration and describes the data that can be reported.

2021-11-08 08:15 UTC, EmilHammarstrand commented
@jpvajda All checks has passed the pipeline now!

2021-11-08 19:00 UTC, jpvajda commented
@EmilHammarstrand Thanks! There is a still my  description content question to resolve, just see the comment I made.

2021-11-09 13:59 UTC, jpvajda approved these changes

2021-11-09 13:59 UTC, merged