feat(pack) Added Amazon Athena
newrelic/newrelic-quickstarts pull request #534
Opened 2021-11-01 12:12 UTC by EmilHammarstrand

# Summary

Added dasboard for Amazon Athena.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2021-11-01 12:13 UTC, EmilHammarstrand commented
I have same question here as in the aws-qldb pack, should I create any alerts on these packs?

2021-11-06 16:22 UTC, jpvajda requested changes

2021-11-06 16:22 UTC, jpvajda commented on quickstarts/aws/amazon-athena/config.yml
> +  Check out the [documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-athena-monitoring-integration) to learn more about New Relic monitoring for A
@bradleycamacho any suggestions on this description? Similar to my other comment in another PR, why not take the content from the docs page and use that?

New Relic offers an integration for reporting your Amazon Athena data. This document explains how to activate this integration and describes the data that can be reported.

2021-11-09 13:59 UTC, jpvajda approved these changes

2021-11-09 13:59 UTC, merged