chore(update documentation): Added a hosted PDF and updated docs link
newrelic/newrelic-quickstarts pull request #555
Opened 2021-11-10 15:47 UTC by nr-jbiggley

# Summary

Updated the documentation link to refer to a PDF doc that is hosted in the Quickstart folder.

2021-11-10 15:48 UTC, nr-jbiggley commented
Also added an update to the dashboard.

2021-11-10 23:15 UTC, jpvajda commented on quickstarts/gigamon/config.yml
> +    description: An overview of the architecture and deployment methodology for Gigamon Hawk integrated with New Relic
```suggestion
    description: | 
        An overview of the architecture and deployment methodology for Gigamon Hawk integrated with New Relic
```

2021-11-10 23:16 UTC, jpvajda requested changes
I made some suggestions on the documentation URL / description.

2021-11-10 23:16 UTC, jpvajda commented on quickstarts/gigamon/config.yml
> +    url: https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/gigamon/Gigamon New Relic Integration.pdf
```suggestion
    url: >- 
       https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/gigamon/Gigamon New Relic Integration.pdf
```

2021-11-11 13:45 UTC, nr-jbiggley commented
> I made some suggestions on the documentation URL / description.

Thanks for the feedback, @jpvajda

2021-11-11 21:34 UTC, jpvajda approved these changes

2021-11-11 21:35 UTC, merged