fix: Fix the correcrt link to the docs
newrelic/newrelic-quickstarts pull request #704
Opened 2022-01-20 16:08 UTC by ykarlinski-newrelic

# Summary
We had a 404 with the docs. PR is the fix

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-01-22 17:09 UTC, jpvajda requested changes

2022-01-22 17:09 UTC, jpvajda commented on quickstarts/mlops/sagemaker/config.yml
>      description: Documentation on the Amazon SageMaker integration
```suggestion
    description: | 
        Documentation on the Amazon SageMaker integration
```

2022-01-22 17:09 UTC, jpvajda commented on quickstarts/mlops/sagemaker/config.yml
> +    url: https://docs.newrelic.com/docs/mlops/integrations/aws-sagemaker-mlops-integration/
```suggestion
    url:  >- 
       https://docs.newrelic.com/docs/mlops/integrations/aws-sagemaker-mlops-integration/
```

2022-01-22 17:10 UTC, jpvajda commented
I made some suggestions to the description and URL format under documentation, please review the [contributor guide](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#documentation) for details on why I am suggestion this. Thanks for the contribution.

2022-01-23 09:01 UTC, ykarlinski-newrelic commented
Commiting reviewer changes

2022-01-24 16:02 UTC, jpvajda approved these changes

2022-01-24 16:02 UTC, merged