fix: Add dummy install plan to oma-data-gov
newrelic/newrelic-quickstarts pull request #795
Opened 2022-02-07 13:10 UTC by JimHagan

# Summary

At the recommendation from some people like Stijn and others in `help-newreic-io` I've created a `dummy` install plan in order to allow users to have relatively effortless dashboard install.

## Pre merge checklist

- [✅ ] Did you check you NRQL syntax? - Does it work?
- [ ✅] Did you check your dashboard image quality? -  Do they look good?
- [✅ ] Did you check that your alerts actually work?
- [ ✅] Did you include an InstallPlan and Documentation reference?
- [✅ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ✅] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-02-07 15:54 UTC, jpvajda requested changes

2022-02-07 15:54 UTC, jpvajda commented on install/solutions-hub/dashboards/install.yml
> +target:
I'm not sure if the unknown value will cause an issue here. Was this what you were instructed to do here @JimHagan ?

2022-02-07 19:54 UTC, jpvajda approved these changes

2022-02-07 19:54 UTC, jpvajda commented on install/solutions-hub/dashboards/install.yml
> +target:
We confirmed with @jbeveland27 what will occur in the UI in this case, and though it's not ideal it did identify a potential improvement for us to look at.

2022-02-07 19:59 UTC, jpvajda commented
This is approved now, but  I wanted to double check with @JimHagan if he's ok with the current UI experience that would show the user this type of unknown, unknown message in the guided install UI.

![Screen Shot 2022-02-07 at 10 27 06 AM](https://user-images.githubusercontent.com/1395158/152862371-2f24c467-9f5d-4b99-9b59-72424f22ce47.png)

2022-02-08 22:44 UTC, JimHagan commented
@jpvajda this would be a decent compromise experience at present.  Thanks.

2022-02-08 23:23 UTC, merged