Feat: new Datazoom quickstart (partner)
newrelic/newrelic-quickstarts pull request #928
Opened 2022-03-17 16:28 UTC by jcountsNR

# Summary

New Datazoom quickstart. 1 Dashbaord, 2 images, install plan.

## Pre merge checklist

- [X ] Did you check you NRQL syntax? - Does it work?
- [ X] Did you check your dashboard image quality? -  Do they look good?
- [ X] Did you include an InstallPlan and Documentation reference?
- [ X] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ X] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

2022-03-21 18:59 UTC, jpvajda requested changes

2022-03-21 18:59 UTC, jpvajda commented on quickstarts/datazoom/config.yml
> +title: Datazoom Quickstart
```suggestion
title: Datazoom 
```

2022-03-21 18:59 UTC, jpvajda commented on quickstarts/datazoom/config.yml
> +title: Datazoom Quickstart
Thanks for the contribution!  I don't think we need to call it a quickstart in the title as it's implicitly a quickstart.

2022-03-21 18:59 UTC, jpvajda commented on quickstarts/datazoom/config.yml
> +  The Datazoom quickstart provides a fast and easy launching point into video metrics built on top of New Relic One Dashboards, allowing you to gain insights about your viewers, content, ads and your
```suggestion
  The Datazoom quickstart provides a fast and easy launching point into video metrics built on top of New Relic One dashboards, allowing you to gain insights about your viewers, content, ads and your platform's performance. Customize the dashboard to use only the metrics that fit your goals and easily edit metric calculations and tailor them to your needs.
```

2022-03-21 19:27 UTC, jcountsNR commented
@jpvajda , good callout. I updated them, let me know how it looks.

2022-03-23 21:56 UTC, jcountsNR commented
@jpvajda  any updates on this one? It should be good to go.

2022-03-23 23:23 UTC, jpvajda approved these changes

2022-03-23 23:26 UTC, jpvajda requested changes

2022-03-23 23:26 UTC, jpvajda commented on quickstarts/datazoom/config.yml
> +name: datazoom-quickstart
```suggestion
name: datazoom
```

2022-03-23 23:26 UTC, jpvajda commented on quickstarts/datazoom/config.yml
> +name: datazoom-quickstart
We are recommended we don't use quickstart in our names and titles as it's redundant.

2022-03-23 23:26 UTC, jpvajda commented on quickstarts/datazoom/config.yml
> +  - name: Installation Docs
```suggestion
  - name: Installation docs
```

2022-03-23 23:26 UTC, jpvajda commented on quickstarts/datazoom/config.yml
> +  - name: Installation Docs
gotta watch that sentence case.  😉

2022-03-23 23:26 UTC, jpvajda commented
@jcountsNR I caught a few more things, I made some suggestions.

2022-03-24 16:15 UTC, jpvajda approved these changes

2022-03-24 16:15 UTC, merged