Feat: Netlify Logs quickstart
newrelic/newrelic-quickstarts pull request #951
Opened 2022-03-24 14:59 UTC by NetlifyMatt

New files for the Netlify Logs quickstart and updates for the Netlify Builds quickstart (name updates and associated files).

# Summary

Creating new files for the Netlify Logs quickstart and updating the name and file structure for the existing Netlify Builds quickstart.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

![netlify-logs01](https://user-images.githubusercontent.com/79875905/159945404-071800a9-50ad-449e-9e0a-81877fb500b9.png)
![netlify-logs02](https://user-images.githubusercontent.com/79875905/159945414-e699a9f0-121b-4b37-93a2-c1ff75bcfd27.png)

2022-03-25 19:58 UTC, jpvajda commented
This looks to have a conflict in `quickstarts/netlify/config.yml` can you take a look at that @NetlifyMatt or @jcountsNR

2022-03-25 20:05 UTC, jpvajda requested changes

2022-03-25 20:05 UTC, jpvajda commented on quickstarts/netlify/netlify-logs/config.yml
> +  - name: Configuration Docs
```suggestion
  - name: Configuration docs
```

2022-03-25 20:06 UTC, aaronbassett commented
Hey folks I'm trying to get PR #932 reverted as it deleted some images which are required by the Netlify quickstart. This will probably impact this PR as well as the directory structure has changed.

Also, the change in directory structure will mean that the [image URL in this markdown widget](https://github.com/newrelic/newrelic-quickstarts/blob/c17ef1252ea427c88e4592a5b446abce1bcdc1c9/quickstarts/netlify/dashboards/netlify.json#L70) will need to be updated too

2022-03-28 17:52 UTC, jcountsNR commented
@jpvajda  done. It looks like the only conflict was on the name which reverted. @aaronbassett , the link should still work since there the netlify/images dir is still correct.

2022-03-28 19:54 UTC, jpvajda approved these changes

2022-03-28 20:22 UTC, jpvajda commented
closing for https://github.com/newrelic/newrelic-quickstarts/pull/967

2022-03-28 20:22 UTC, closed without merging